@extends('layouts.app')
@section('title','تأیید شماره موبایل')
@section('content')
<div class="otp-page"><div class="otp-card"><div class="otp-brand"><span><x-icon name="lock" size="22" /></span><div><strong>تأیید امن</strong><small>ورود به فروشگاه فایل</small></div></div><div class="otp-title"><h1>کد تأیید را وارد کنید</h1><p>کد ۶ رقمی به شماره <b dir="ltr">{{ $phone }}</b> ارسال شد.</p></div>@if($errors->any())<div class="otp-alert error">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif@if(session('warning'))<div class="otp-alert warning">{{ session('warning') }}</div>@endif@if(session('success'))<div class="otp-alert success">{{ session('success') }}</div>@endif
<form method="POST" action="{{ route('otp.verify') }}">@csrf<input type="hidden" name="phone" value="{{ $phone }}"><label for="code">کد یک‌بارمصرف</label><input id="code" name="code" class="otp-code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" minlength="6" pattern="[0-9]{6}" placeholder="------" required autofocus dir="ltr"><div class="otp-timer" id="otpTimer" data-seconds="{{ $seconds ?? 120 }}">ارسال مجدد تا <b id="timerValue">{{ $seconds ?? 120 }}</b> ثانیه</div><button class="otp-submit" type="submit">تأیید و ادامه <x-icon name="arrow-left" size="17" /></button></form><div class="otp-resend" id="resendBox" hidden><span>کد را دریافت نکردید؟</span><form method="POST" action="{{ route('otp.resend') }}">@csrf<input type="hidden" name="phone" value="{{ $phone }}"><button type="submit">ارسال مجدد کد</button></form></div><div class="otp-security"><x-icon name="lock" size="16" /><span>کد را با هیچ‌کس به اشتراک نگذارید.</span></div><a class="otp-back" href="{{ route('login') }}">بازگشت به ورود</a></div></div>
@endsection
@push('styles')<style>.otp-page{min-height:680px;display:grid;place-items:center;padding:40px 15px;background:radial-gradient(circle at 50% 0,#eeeaff 0,transparent 42%)}.otp-card{width:min(430px,100%);background:#fff;border:1px solid #e5e7eb;border-radius:24px;padding:28px;box-shadow:0 22px 70px #10182812}.otp-brand{display:flex;align-items:center;gap:10px}.otp-brand>span{width:42px;height:42px;border-radius:13px;background:#f0edff;color:#6541d8;display:grid;place-items:center}.otp-brand strong,.otp-brand small{display:block}.otp-brand small{font-size:10px;color:#98a2b3;margin-top:2px}.otp-title{text-align:center;margin:28px 0 22px}.otp-title h1{font-size:21px;margin:0 0 7px}.otp-title p{font-size:12px;color:#667085;margin:0}.otp-title b{color:#111827}.otp-card label{display:block;font-size:12px;font-weight:800;margin-bottom:7px}.otp-code{width:100%;box-sizing:border-box;text-align:center;letter-spacing:11px;font-size:27px;font-weight:900;padding:12px;border:1px solid #dfe3ea;border-radius:13px;outline:0}.otp-code:focus{border-color:#6541d8;box-shadow:0 0 0 4px #6541d815}.otp-timer{text-align:center;color:#667085;font-size:11px;margin:13px 0}.otp-timer b{color:#111827}.otp-submit{width:100%;display:flex;align-items:center;justify-content:center;gap:7px;border:0;border-radius:13px;padding:12px;background:#111827;color:#fff;font:inherit;font-weight:900;cursor:pointer}.otp-submit:hover{background:#6541d8}.otp-alert{padding:10px 12px;border-radius:11px;margin-bottom:13px;font-size:11px}.otp-alert.error{background:#fff0f0;color:#a33}.otp-alert.warning{background:#fff8e6;color:#8a5a00}.otp-alert.success{background:#ecfdf3;color:#087443}.otp-resend{text-align:center;margin:16px 0;font-size:11px;color:#667085}.otp-resend form{display:inline}.otp-resend button{border:0;background:none;color:#6541d8;font:inherit;font-weight:800;cursor:pointer;margin-right:5px}.otp-security{display:flex;align-items:center;justify-content:center;gap:6px;margin-top:18px;padding:10px;border-radius:11px;background:#f8fafc;color:#667085;font-size:10px}.otp-security svg{color:#6541d8}.otp-back{display:block;text-align:center;margin-top:18px;color:#667085;font-size:11px}.otp-back:hover{color:#6541d8}@media(max-width:500px){.otp-card{padding:22px}.otp-code{font-size:23px;letter-spacing:8px}}
</style>@endpush
@push('scripts')<script>(function(){const timer=document.getElementById('otpTimer'),value=document.getElementById('timerValue'),resend=document.getElementById('resendBox');if(!timer)return;let seconds=Number(timer.dataset.seconds||120);const tick=()=>{value.textContent=Math.max(0,seconds);if(seconds<=0){timer.hidden=true;resend.hidden=false;return}seconds--;setTimeout(tick,1000)};tick();const code=document.getElementById('code');code?.addEventListener('input',()=>{code.value=code.value.replace(/\D/g,'').slice(0,6)})})();</script>@endpush
