@extends('layouts.app')
@section('title','سبد خرید')
@section('description','مدیریت فایل‌های انتخاب‌شده و ادامه خرید')
@section('content')
<div class="container cart-page">
<div class="ds-page-head"><div><h1>سبد خرید</h1><p>فایل‌های انتخاب‌شده را بررسی کنید و سپس به پرداخت بروید.</p></div><a class="ds-btn" href="{{ route('products.index') }}"><x-icon name="search" size="16"/> ادامه خرید</a></div>
@if(session('cart_error'))<div class="alert-error">{{ session('cart_error') }}</div>@endif
@if($products->isEmpty())
<div class="cart-box" style="padding:60px 20px;text-align:center"><x-icon name="cart" size="44"/><h2 style="font-size:17px">سبد خرید شما خالی است</h2><p style="color:#8a94a6;font-size:11px">محصول موردنیازتان را از فروشگاه انتخاب کنید.</p><a class="ds-btn ds-btn-primary" href="{{ route('products.index') }}">مشاهده فروشگاه</a></div>
@else
<div class="cart-layout"><div>
<div class="cart-box"><div class="cart-title"><strong>فایل‌های انتخاب‌شده</strong><span>{{ $products->count() }} فایل</span></div>
@foreach($products as $product)<div class="cart-row"><a class="cart-product" href="{{ route('product.show',$product) }}"><div class="cart-thumb"><img src="{{ $product->thumbnail_url }}" alt="{{ $product->title }}"></div><div><strong>{{ $product->title }}</strong><div class="muted">فایل دیجیتال · دریافت پس از پرداخت</div></div></a><div class="cart-price">{{ number_format($product->price) }} تومان</div><div class="cart-actions"><form method="POST" action="{{ route('cart.later',$product) }}">@csrf<button title="بعداً می‌خرم" aria-label="بعداً می‌خرم"><x-icon name="heart" size="16"/></button></form><form method="POST" action="{{ route('cart.remove',$product) }}">@csrf @method('DELETE')<button title="حذف" aria-label="حذف"><x-icon name="trash" size="16"/></button></form></div></div>@endforeach</div>
@if($recommendations->count())<section class="cart-box recommendations"><h2>پیشنهادهای مرتبط با سبد شما</h2><div class="mini-products">@foreach($recommendations as $suggestion)<a href="{{ route('product.show',$suggestion) }}" class="mini-product"><span><img src="{{ $suggestion->thumbnail_url }}" alt="" style="width:36px;height:36px;object-fit:cover;border-radius:10px"></span><div><strong>{{ $suggestion->title }}</strong><small>{{ number_format($suggestion->price) }} تومان</small></div></a>@endforeach</div></section>@endif
</div>
<aside class="cart-summary-box"><h2>خلاصه خرید</h2><div class="summary-line"><span>مجموع فایل‌ها</span><strong>{{ number_format($subtotal) }} تومان</strong></div><div class="discount-box"><h3>کد تخفیف</h3>@if(session('discount_code'))<div class="discount-active"><span>{{ session('discount_code') }} اعمال شده</span><form method="POST" action="{{ route('cart.discount.remove') }}">@csrf @method('DELETE')<button>حذف کد</button></form></div>@else<form method="POST" action="{{ route('cart.discount') }}">@csrf<input type="text" name="code" placeholder="کد تخفیف"><button type="submit">اعمال</button></form>@endif@if(session('discount_error'))<div class="cart-message error">{{ session('discount_error') }}</div>@endif@if(session('discount_success'))<div class="cart-message success">{{ session('discount_success') }}</div>@endif</div><div class="cart-summary-row"><span>تخفیف</span><strong>-{{ number_format($discount) }} تومان</strong></div><div class="summary-line saving"><span>سود شما</span><strong>{{ number_format($discount) }} تومان</strong></div><hr><div class="cart-summary-total"><span>مبلغ نهایی</span><strong>{{ number_format($total) }} تومان</strong></div><a class="checkout-btn" href="{{ route('checkout') }}">ادامه و تسویه‌حساب <x-icon name="arrow-left" size="16"/></a><p class="summary-note">پرداخت امن و دریافت فایل پس از تأیید پرداخت</p></aside></div>
@endif
@if($laterProducts->count())<section class="cart-box later-box"><div class="cart-title"><h2>بعداً می‌خرم</h2><span>{{ $laterProducts->count() }} فایل</span></div>@foreach($laterProducts as $product)<div class="later-row"><div><strong>{{ $product->title }}</strong><div class="muted">{{ number_format($product->price) }} تومان</div></div><form method="POST" action="{{ route('cart.move',$product) }}">@csrf<button class="later-btn" type="submit">افزودن به سبد</button></form></div>@endforeach</section>@endif
</div>
@endsection