@extends('layouts.app')
@section('title','فروشگاه فایل | مرجع فایل‌های دیجیتال')
@section('description','خرید و بررسی فایل‌های دیجیتال با جستجوی هوشمند و دسته‌بندی‌های کاربردی')
@section('content')
<div class="dj-home">
<section class="dj-hero-premium container" id="homeHero" dir="rtl" aria-label="محتوای ویژه فروشگاه">
<div class="hero-slider-stage">
@php($heroSlides=[
['eyebrow'=>'یادگیری و رشد','title'=>'مسیر یادگیریت را بهتر بساز','description'=>'فایل‌ها، منابع و محتوای آموزشی موردنیازت را یکجا پیدا کن.','cta'=>'مشاهده منابع آموزشی','href'=>route('search',['q'=>'آموزشی یادگیری دانشگاه']),'image'=>'1.png'],
['eyebrow'=>'منابع حرفه‌ای','title'=>'ابزار درست، شروع یک نتیجه بهتر است','description'=>'فایل‌ها و منابع کاربردی برای کار، یادگیری و رشد حرفه‌ای.','cta'=>'کشف منابع حرفه‌ای','href'=>route('products.index'),'image'=>'2.png'],
['eyebrow'=>'کار و فرصت','title'=>'مهارتت را به فرصت تبدیل کن','description'=>'منابعی برای ساختن مسیر شغلی بهتر و حرفه‌ای‌تر.','cta'=>'مشاهده منابع شغلی','href'=>route('search',['q'=>'کار استخدام رزومه']),'image'=>'3.png'],
['eyebrow'=>'فناوری و خلاقیت','title'=>'ابزار بهتر، نتیجه بهتر','description'=>'منابع کاربردی برای فناوری، طراحی و تولید محتوای حرفه‌ای.','cta'=>'کشف فایل‌ها','href'=>route('search',['q'=>'فناوری طراحی تولید محتوا']),'image'=>'4.png']])
@foreach($heroSlides as $index=>$slide)
<article class="hero-slide {{ $index===0?'is-active':'' }}" data-index="{{ $index }}" aria-hidden="{{ $index===0?'false':'true' }}"><div class="hero-copy"><span class="hero-eyebrow">{{ $slide['eyebrow'] }}</span>@if($index===0)<h1>{{ $slide['title'] }}</h1>@else<h2>{{ $slide['title'] }}</h2>@endif<p>{{ $slide['description'] }}</p><a class="hero-cta" href="{{ $slide['href'] }}">{{ $slide['cta'] }} <x-icon name="arrow-left" size="16"/></a></div><div class="hero-art"><img src="{{ route('media.legacy',['path'=>'Banners/'.$slide['image']]) }}" alt="" width="900" height="520" loading="{{ $index===0?'eager':'lazy' }}" fetchpriority="{{ $index===0?'high':'auto' }}" draggable="false"></div></article>
@endforeach
<div class="hero-controls"><button type="button" class="hero-arrow" data-hero-prev aria-label="رفتن به اسلاید قبلی"><x-icon name="arrow-right" size="18"/></button><button type="button" class="hero-arrow" data-hero-next aria-label="رفتن به اسلاید بعدی"><x-icon name="arrow-left" size="18"/></button><div class="hero-progress-wrap"><span data-hero-count>01 / 04</span><span class="hero-progress"><i data-hero-progress></i></span></div><div class="hero-dots" role="tablist" aria-label="انتخاب اسلاید">@foreach($heroSlides as $index=>$slide)<button type="button" role="tab" aria-label="اسلاید {{ $index+1 }}" aria-selected="{{ $index===0?'true':'false' }}" data-hero-dot="{{ $index }}">{{ str_pad($index+1,2,'0',STR_PAD_LEFT) }}</button>@endforeach</div></div>
</div></section>
<section class="dj-section container" id="quick-categories"><div class="dj-category-heading"><span class="section-kicker">دسته‌بندی‌ها</span><h2>هر آنچه برای یادگیری و پیشرفت نیاز داری</h2><p>فایل‌ها و منابع موردنیازت را از میان دسته‌بندی‌های مختلف پیدا کن.</p></div><div class="premium-category-grid">@foreach($quickCategories as $category)@php($categoryUrl=$category['id']?route('search',['category'=>$category['id']]):route('search',['q'=>$category['title']]))<a class="premium-category-card accent-{{ $category['accent'] }}" href="{{ $categoryUrl }}"><div class="premium-category-art"><img src="{{ route('media.category',$category['slug']) }}" alt="{{ $category['title'] }}" width="600" height="450" loading="lazy"></div><div class="premium-category-content"><strong>{{ $category['title'] }}</strong><p>{{ $category['description'] }}</p><span class="premium-category-action">مشاهده فایل‌ها <x-icon name="arrow-left" size="15"/></span></div></a>@endforeach</div></section>
<section class="dj-section container"><div class="dj-section-head"><div><span class="section-kicker">انتخاب هوشمند</span><h2>محبوب‌ترین فایل‌ها</h2><p>محصولات منتخب بر اساس داده‌های واقعی فروشگاه</p></div><a href="{{ route('products.index') }}">مشاهده همه <x-icon name="arrow-left" size="14"/></a></div><div class="dj-products">@forelse($products as $product)<article class="dj-product"><a href="{{ route('product.show',$product) }}"><img src="{{ $product->thumbnail_url }}" alt="{{ $product->title }}" width="320" height="205" loading="lazy"><div class="dj-product-body"><div class="meta">{{ $product->category?->name ?: 'فایل دیجیتال' }} · #{{ $product->id }}</div><h3>{{ $product->title }}</h3><div class="price">{{ number_format($product->price) }} تومان</div></div></a><form method="POST" action="{{ route('cart.add',$product) }}">@csrf<button class="cart" type="submit" aria-label="افزودن به سبد"><x-icon name="cart" size="18"/></button></form></article>@empty<div class="dj-empty">هنوز محصول منتشرشده‌ای وجود ندارد.</div>@endforelse</div></section>
@if($popularCategories->count())<section class="dj-section container"><div class="dj-section-head"><div><span class="section-kicker">محبوب‌ترین دسته‌ها</span><h2>از مسیرهای پرطرفدار شروع کن</h2></div></div><div class="popular-category-strip">@foreach($popularCategories as $category)<a href="{{ route('search',['category'=>$category->id]) }}"><span class="popular-category-icon"><x-icon name="category" size="19"/></span><strong>{{ $category->name }}</strong><small>{{ number_format($category->published_products_count) }} فایل</small><x-icon name="arrow-left" size="14"/></a>@endforeach</div></section>@endif
<section class="container"><div class="dj-feature blue"><div><span>قبل از خرید مطمئن شو</span><h2>محتوای واقعی فایل را ببین</h2><p>پیش‌نمایش، اطلاعات فایل و پیشنهادهای مرتبط را یکجا ببین و با اطمینان انتخاب کن.</p><a class="dj-btn" href="{{ route('products.index') }}">مشاهده فروشگاه <x-icon name="arrow-left" size="16"/></a></div><div class="dj-feature-art"><img src="{{ route('media.cover','pdf') }}" alt="پیش‌نمایش فایل" width="420" height="300" loading="lazy"></div></div></section>
<section class="dj-section container"><div class="dj-section-head"><div><span class="section-kicker">پرفروش‌ترین فایل‌ها</span><h2>انتخاب‌هایی که بیشتر خریده شده‌اند</h2></div></div><div class="dj-products dj-products-compact">@forelse($bestSellingProducts as $product)<article class="dj-product"><a href="{{ route('product.show',$product) }}"><img src="{{ $product->thumbnail_url }}" alt="{{ $product->title }}" width="320" height="205" loading="lazy"><div class="dj-product-body"><div class="meta">پرفروش · {{ $product->category?->name ?: 'فایل دیجیتال' }}</div><h3>{{ $product->title }}</h3><div class="price">{{ number_format($product->price) }} تومان</div></div></a><form method="POST" action="{{ route('cart.add',$product) }}">@csrf<button class="cart" type="submit" aria-label="افزودن به سبد"><x-icon name="cart" size="18"/></button></form></article>@empty<div class="dj-empty">هنوز خریدی ثبت نشده است.</div>@endforelse</div></section>
<section class="container"><div class="dj-feature dark"><div><span>برای فروشندگان</span><h2>فایل خودت را به فروش برسان</h2><p>فایل را ارسال کن؛ بررسی، تأیید و مدیریت فروش در همان پنل انجام می‌شود.</p>@auth<a class="dj-btn" href="{{ route('account.dashboard') }}">ورود به پنل <x-icon name="arrow-left" size="16"/></a>@else<a class="dj-btn" href="{{ route('login') }}">شروع کار <x-icon name="arrow-left" size="16"/></a>@endauth</div><div class="dj-feature-art"><img src="{{ route('media.cover','file') }}" alt="فروش فایل" width="420" height="300" loading="lazy"></div></div></section>
<section class="dj-section container"><div class="dj-section-head"><div><span class="section-kicker">فایل‌های کاربردی</span><h2>برای کارهای روزمره آماده باش</h2></div></div><div class="dj-products dj-products-compact">@forelse($usefulProducts as $product)<article class="dj-product"><a href="{{ route('product.show',$product) }}"><img src="{{ $product->thumbnail_url }}" alt="{{ $product->title }}" width="320" height="205" loading="lazy"><div class="dj-product-body"><div class="meta">کاربردی · {{ $product->category?->name ?: 'فایل دیجیتال' }}</div><h3>{{ $product->title }}</h3><div class="price">{{ number_format($product->price) }} تومان</div></div></a><form method="POST" action="{{ route('cart.add',$product) }}">@csrf<button class="cart" type="submit" aria-label="افزودن به سبد"><x-icon name="cart" size="18"/></button></form></article>@empty<div class="dj-empty">هنوز فایل کاربردی وجود ندارد.</div>@endforelse</div></section>
<section class="dj-section container"><div class="dj-section-head"><div><span class="section-kicker">جدیدترین فایل‌ها</span><h2>تازه‌ترین فایل‌های فروشگاه</h2></div><a href="{{ route('products.index',['sort'=>'latest']) }}">مشاهده همه <x-icon name="arrow-left" size="14"/></a></div><div class="dj-products dj-products-compact">@forelse($latestProducts as $product)<article class="dj-product"><a href="{{ route('product.show',$product) }}"><img src="{{ $product->thumbnail_url }}" alt="{{ $product->title }}" width="320" height="205" loading="lazy"><div class="dj-product-body"><div class="meta">جدید · {{ $product->category?->name ?: 'فایل دیجیتال' }}</div><h3>{{ $product->title }}</h3><div class="price">{{ number_format($product->price) }} تومان</div></div></a><form method="POST" action="{{ route('cart.add',$product) }}">@csrf<button class="cart" type="submit" aria-label="افزودن به سبد"><x-icon name="cart" size="18"/></button></form></article>@empty<div class="dj-empty">هنوز محصول تازه‌ای منتشر نشده است.</div>@endforelse</div></section>
@if($latestPosts->count())<section class="dj-section container"><div class="dj-section-head"><div><span class="section-kicker">راهنما</span><h2>آخرین مقالات</h2></div><a href="{{ route('blog.index') }}">همه مقالات <x-icon name="arrow-left" size="14"/></a></div><div class="dj-blog-grid">@foreach($latestPosts as $post)<a class="dj-blog-card" href="{{ route('blog.show',$post->slug) }}">@if($post->image)<img src="{{ str_starts_with($post->image,'http')?$post->image:asset($post->image) }}" alt="{{ $post->title }}" loading="lazy">@else<img src="{{ route('media.cover','file') }}" alt="{{ $post->title }}" loading="lazy">@endif<h3>{{ $post->title }}</h3><p>{{ \Illuminate\Support\Str::limit(strip_tags($post->excerpt ?: $post->body),100) }}</p></a>@endforeach</div></section>@endif
</div>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('css/home-premium.css') }}"><link rel="stylesheet" href="{{ asset('css/home-hero-slider.css') }}">@endpush
@push('scripts')<script src="{{ asset('js/home-hero-slider.js') }}" defer></script>@endpush
