@extends('layouts.app')
@section('title',$q ? 'جستجوی '.$q.' | فایل‌مارکت' : 'فروشگاه فایل')
@section('description','فروشگاه یکپارچه فایل‌های دیجیتال با جستجوی هوشمند و پیشنهادهای مرتبط')
@section('content')
<div class="container store-page"><div class="store-head"><div><span>فروشگاه فایل</span><h1>{{ $q ? 'نتایج جستجو برای «'.$q.'»' : 'همه فایل‌ها' }}</h1><p>{{ $q ? 'نتایج بر اساس عنوان، توضیحات و محتوای واقعی فایل‌ها رتبه‌بندی شده‌اند.' : 'فایل‌های دیجیتال را با همان کارت و تجربه خرید صفحه محصول بررسی کنید.' }}</p></div><form class="store-search" action="{{ route('search') }}"><input name="q" value="{{ $q }}" placeholder="نام فایل یا نیازتان را جستجو کنید"><button type="submit">جستجو</button></form></div>
<div class="store-toolbar"><strong>{{ number_format($products->total()) }} محصول</strong><div class="store-sort"><a class="active" href="{{ request()->fullUrlWithQuery(['page'=>1]) }}">مرتبط‌ترین</a><a href="{{ request()->fullUrlWithQuery(['sort'=>'newest','page'=>1]) }}">جدیدترین</a><a href="{{ request()->fullUrlWithQuery(['sort'=>'cheap','page'=>1]) }}">ارزان‌ترین</a><a href="{{ request()->fullUrlWithQuery(['sort'=>'expensive','page'=>1]) }}">گران‌ترین</a></div></div>
<div class="store-products-grid">@forelse($products as $product)<div class="store-product-tile"><x-store-product-card :product="$product" :reason="isset($product->evidence)&&count($product->evidence) ? 'تطابق با محتوای فایل' : null"/><form method="POST" action="{{ route('cart.add',$product) }}">@csrf<button type="submit"><x-icon name="cart" size="15"/> افزودن به سبد</button></form></div>@empty<div class="store-empty"><h2>محصولی پیدا نشد</h2><p>عبارت دیگری را امتحان کنید.</p></div>@endforelse</div><div class="pagination">{{ $products->links() }}</div></div>
@endsection
@push('styles')<style>.store-page{max-width:1280px;padding:28px 16px 70px}.store-head{display:grid;grid-template-columns:1fr minmax(320px,480px);gap:28px;align-items:end;margin-bottom:22px}.store-head>div>span{font-size:10px;color:#98a2b3}.store-head h1{font-size:27px;margin:6px 0}.store-head p{font-size:11px;color:#667085}.store-search{display:flex;gap:7px}.store-search input{flex:1;min-width:0;height:44px;border:1px solid #d0d5dd;border-radius:12px;padding:0 13px;font:inherit}.store-search button{border:0;border-radius:12px;background:#111827;color:#fff;padding:0 18px;cursor:pointer;font:inherit;font-size:11px;font-weight:900}.store-toolbar{display:flex;justify-content:space-between;align-items:center;gap:15px;border:1px solid #eaecf0;border-radius:14px;background:#fff;padding:11px 14px;margin-bottom:14px;font-size:11px}.store-sort{display:flex;gap:6px;flex-wrap:wrap}.store-sort a{padding:7px 9px;border-radius:8px;color:#667085}.store-sort a.active{background:#eef2ff;color:#4338ca;font-weight:800}.store-products-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:13px}.store-product-tile{position:relative;min-width:0}.store-product-tile .store-product-card{height:100%}.store-product-tile form{margin-top:7px}.store-product-tile form button{width:100%;display:flex;align-items:center;justify-content:center;gap:6px;border:1px solid #d0d5dd;background:#fff;border-radius:10px;padding:9px;cursor:pointer;font:inherit;font-size:10px;font-weight:900}.store-empty{grid-column:1/-1;text-align:center;background:#fff;border:1px solid #eaecf0;border-radius:18px;padding:60px 20px}.store-empty h2{font-size:17px}.store-empty p{font-size:10px;color:#98a2b3}@media(max-width:1050px){.store-products-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){.store-head{grid-template-columns:1fr}.store-products-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.store-toolbar{align-items:flex-start;flex-direction:column}}@media(max-width:480px){.store-products-grid{grid-template-columns:1fr}.store-search button{padding:0 12px}}</style>@endpush
