@php($trustBadges=json_decode((string)\App\Models\SiteSetting::getValue('trust_badges','[]'),true)?:[])
<footer class="dj-footer-capture">
<div class="footer-newsletter-band"><div class="footer-newsletter-copy"><span>پیشنهادهای مناسب شما</span><strong>از فروش‌های ویژه باخبر شوید</strong><p>ایمیل خود را وارد کنید تا فایل‌های تازه و پیشنهادهای مرتبط را از دست ندهید.</p></div><form action="{{ route('newsletter.subscribe') }}" method="POST" class="footer-newsletter-form" id="newsletter">@csrf<input type="email" name="email" value="{{ old('email') }}" placeholder="ایمیل خود را وارد کنید" autocomplete="email" dir="ltr" required><button type="submit">تأیید</button></form></div>
<div class="footer-capture-grid">
<section class="footer-about"><h3>درباره فایل‌مارکت</h3><p>اگر به دنبال فایل کاربردی هستید یا می‌خواهید فایل خود را عرضه کنید، اینجا بستری ساده و مطمئن برای پیدا کردن، بررسی و خرید فایل‌های دیجیتال است.</p><div class="footer-trust"><div class="footer-trust-title">مجوزها و نمادهای اعتماد</div><div class="footer-badges">@forelse($trustBadges as $badge)@if(!empty($badge['html']))<div class="footer-badge-html">{!! $badge['html'] !!}</div>@elseif(!empty($badge['image']))<a href="{{ $badge['url']??'#' }}" target="_blank" rel="noopener" title="{{ $badge['title']??'نماد اعتماد' }}"><img src="{{ $badge['image'] }}" alt="{{ $badge['title']??'نماد اعتماد' }}" loading="lazy"></a>@endif @empty<div class="footer-badge-empty">نمادهای اعتماد را از تنظیمات سایت ثبت کنید.</div>@endforelse</div></div></section>
<section><h3>دسترسی سریع</h3><ul><li><a href="{{ route('page.contact') }}">تماس با ما</a></li><li><a href="{{ route('page.terms') }}">قوانین خرید</a></li><li><a href="{{ route('page.privacy') }}">حریم خصوصی</a></li><li><a href="{{ route('page.faq') }}">سؤالات متداول</a></li><li><a href="{{ route('support.index') }}">پشتیبانی</a></li></ul></section>
<section><h3>فایل‌مارکت</h3><ul><li><a href="{{ route('products.index') }}">فروشگاه فایل</a></li><li><a href="{{ route('blog.index') }}">آخرین مطالب</a></li><li><a href="{{ route('page.seller.terms') }}">قوانین فروشندگان</a></li>@auth<li><a href="{{ route('account.dashboard') }}">پنل کاربری</a></li>@else<li><a href="{{ route('login') }}">ورود و ثبت‌نام</a></li>@endauth</ul></section>
<section class="footer-social"><h3>شبکه‌های اجتماعی</h3><p>اخبار، آموزش‌ها و پیشنهادهای تازه فایل‌مارکت را دنبال کنید.</p><div class="footer-social-list"><a href="#" aria-label="روبیکا"><span>R</span> روبیکا</a><a href="#" aria-label="تلگرام"><span>✈</span> تلگرام</a><a href="#" aria-label="اینستاگرام"><span>◎</span> اینستاگرام</a><a href="#" aria-label="لینکدین"><span>in</span> لینکدین</a></div></section>
</div>
<div class="footer-bottom"><div class="footer-stats"><div><span class="footer-stat-icon"><x-icon name="users" size="25"/></span><b>{{ \App\Models\User::count() }}+</b><small>کاربر</small></div><div><span class="footer-stat-icon"><x-icon name="file" size="25"/></span><b>{{ \App\Models\Product::where('is_published',true)->count() }}+</b><small>فایل منتشرشده</small></div><div><span class="footer-stat-icon"><x-icon name="dashboard" size="25"/></span><b>۲۴</b><small>ساعت در دسترس</small></div><div><span class="footer-stat-icon"><x-icon name="download" size="25"/></span><b>سریع</b><small>دریافت فایل</small></div></div><div class="footer-copy">کلیه حقوق مادی و معنوی این وب‌سایت متعلق به فایل‌مارکت می‌باشد.</div></div>
</footer>
