@extends('account.layout')
@section('title','ارسال محصول')
@section('content')
<div class="panel-hero"><div><h1>ارسال فایل جدید</h1><p>عنوان، توضیحات ساختاریافته، سئو و مشخصات فایل را کامل کنید.</p></div></div>
<form class="panel-widget seller-product-form" method="POST" action="{{ route('seller.products.store') }}">@csrf<div class="panel-widget-head"><h2>اطلاعات محصول</h2></div><div class="seller-product-body">
<label>عنوان محصول<input class="form-input" name="title" value="{{ old('title') }}" maxlength="255" required></label>
<label>دسته‌بندی<select class="form-input" name="category_id" required><option value="">انتخاب دسته‌بندی</option>@foreach($categories->where('level',0) as $parent)<optgroup label="{{ $parent->name }}"><option value="{{ $parent->id }}">{{ $parent->name }}</option>@foreach($categories->where('parent_id',$parent->id) as $child)<option value="{{ $child->id }}">— {{ $child->name }}</option>@endforeach</optgroup>@endforeach</select></label>
<label>قیمت<input class="form-input" type="number" name="price" value="{{ old('price',35000) }}" min="0" required></label>
<label>توضیح کوتاه<textarea class="form-input" name="short_description" rows="4" maxlength="300">{{ old('short_description') }}</textarea><span class="seller-help">برای نمایش در بخش‌های خاص سایت و نتیجه جستجو؛ حداکثر ۳۰۰ حرف.</span></label>
<div class="ds-rich-editor" data-editor><div class="ds-editor-toolbar"><button type="button" data-cmd="bold"><b>درشت</b></button><button type="button" data-cmd="italic"><i>خمیده</i></button><button type="button" data-cmd="underline"><u>زیرخط</u></button><button type="button" data-cmd="formatBlock" data-value="H2">عنوان ۲</button><button type="button" data-cmd="formatBlock" data-value="H3">عنوان ۳</button><button type="button" data-cmd="insertUnorderedList">فهرست</button><button type="button" data-cmd="insertOrderedList">شماره‌ای</button><button type="button" data-cmd="justifyRight">راست‌چین</button><button type="button" data-cmd="createLink">پیوند</button></div><div class="ds-editor-content" contenteditable="true">{!! old('description') !!}</div><textarea class="ds-editor-value" name="description" hidden></textarea></div>
<label>کلمات کلیدی<textarea class="form-input" name="seo_keywords" rows="4" maxlength="5000">{{ old('seo_keywords') }}</textarea><span class="seller-help">هر کلمه یا عبارت را در یک خط یا با ، , - + جدا کنید.</span></label>
<div class="seller-grid"><label>عنوان سئو<input class="form-input" name="meta_title" maxlength="255" value="{{ old('meta_title') }}"></label><label>توضیحات متا<textarea class="form-input" name="meta_description" rows="3" maxlength="320">{{ old('meta_description') }}</textarea></label></div>
<div class="seller-grid"><label>فرمت فایل اصلی<div class="pc3-inline"><select id="sellerFormatSelect" class="form-input ltr"><option value="">انتخاب</option><option>.pdf</option><option>.doc</option><option>.docx</option><option>.ppt</option><option>.pptx</option></select><span>یا</span><input id="sellerFormatManual" class="form-input ltr" placeholder=".pdf"></div><input id="sellerFormat" type="hidden" name="file_format" value="{{ old('file_format') }}"><div id="sellerFormatConfirm" class="seller-confirm" hidden><input id="sellerFormatConfirmed" type="checkbox" name="format_confirmed" value="1"><span>فرمت تشخیص‌داده‌شده را تأیید می‌کنم.</span></div></label><label>تعداد صفحات فایل اصلی<input id="sellerPageCount" class="form-input ltr" type="number" min="0" name="page_count" value="{{ old('page_count') }}"><span class="seller-help">برای PDF، Word و PowerPoint در صورت امکان خودکار تشخیص داده می‌شود.</span></label></div>
<div><strong>فایل‌ها</strong><p class="seller-help">PDF، DOC، DOCX، PPT و PPTX تا ۲۰۰MB.</p><input id="sellerFiles" type="file" multiple accept=".pdf,.doc,.docx,.ppt,.pptx"><div id="uploadStatus" class="seller-status"></div><div id="uploadIds"></div></div><button class="dj-btn" type="submit"><x-icon name="check" size="17"/> ارسال برای بررسی</button></div></form>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('css/product-editor.css') }}"><style>.seller-product-form{overflow:hidden}.seller-product-body{padding:20px;display:grid;gap:15px}.seller-product-body label{display:grid;gap:7px;font-size:11px;font-weight:800}.seller-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.seller-help{font-size:9px;color:#98a2b3;line-height:1.8}.seller-status{font-size:10px;color:#667085;margin-top:8px}.seller-confirm{display:flex!important;align-items:center;gap:7px;padding:9px;border-radius:9px;background:#fff8e7;color:#8a5b00}.seller-confirm input{width:16px}.ltr{direction:ltr}@media(max-width:650px){.seller-grid{grid-template-columns:1fr}}</style>@endpush
@push('scripts')<script src="{{ asset('js/product-editor.js') }}" defer></script><script>(()=>{const input=document.getElementById('sellerFiles'),status=document.getElementById('uploadStatus'),ids=document.getElementById('uploadIds'),form=document.querySelector('.seller-product-form'),format=document.getElementById('sellerFormat'),select=document.getElementById('sellerFormatSelect'),manual=document.getElementById('sellerFormatManual'),confirmBox=document.getElementById('sellerFormatConfirm'),confirmed=document.getElementById('sellerFormatConfirmed'),page=document.getElementById('sellerPageCount');let count=0;select.onchange=()=>{manual.value='';format.value=select.value;confirmBox.hidden=true;confirmed.checked=true};manual.oninput=()=>{let v=manual.value.trim().toLowerCase();if(v&&!v.startsWith('.'))v='.'+v;format.value=v;confirmBox.hidden=true;confirmed.checked=true};async function upload(file){const fd=new FormData();fd.append('file',file);const r=await fetch('{{ route('seller.products.uploads.store') }}',{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:fd});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.message||'خطا');(j.files||[]).forEach(f=>{const hidden=document.createElement('input');hidden.type='hidden';hidden.name='upload_ids[]';hidden.value=f.id;ids.appendChild(hidden);count++;if(!format.value&&f.format){format.value=f.format;manual.value=f.format;confirmBox.hidden=false;confirmed.checked=false}if(f.page_count&&!page.value)page.value=f.page_count});status.textContent='فایل‌های آماده ارسال: '+count}input?.addEventListener('change',async e=>{status.textContent='در حال بارگذاری...';for(const file of e.target.files){try{await upload(file)}catch(err){status.textContent='خطا: '+err.message}}});form?.addEventListener('submit',e=>{if(!count){e.preventDefault();alert('حداقل یک فایل انتخاب کنید.');return}if(!format.value){e.preventDefault();alert('فرمت فایل را مشخص کنید.');return}if(!confirmBox.hidden&&!confirmed.checked){e.preventDefault();alert('فرمت تشخیص‌داده‌شده را تأیید کنید.')}})})();</script>@endpush