<?php
namespace App\Services\Auth;
use App\Models\OtpEvent;use App\Models\OtpSecurity;use App\Services\Phone\IranPhoneValidator;use App\Services\Sms\SmsManager;use Illuminate\Support\Facades\Cache;use RuntimeException;
class OtpService{
 private const EXPIRE_SECONDS=120,RESEND_SECONDS=120,DAILY_LIMIT_NORMAL=3,DAILY_LIMIT_RESTRICTED=2,DAILY_LIMIT_SEVERE=1;
 public function __construct(private SmsManager $sms,private IranPhoneValidator $phoneValidator){}
 public function send(string $phone):bool{$phone=$this->phoneValidator->normalize($phone);if(!$this->phoneValidator->isValid($phone))throw new RuntimeException('شماره موبایل وارد شده معتبر نیست.');$security=OtpSecurity::firstOrCreate(['phone'=>$phone],['daily_count_date'=>now()->toDateString()]);if($security->sms_blocked_until&&now()->lt($security->sms_blocked_until))throw new RuntimeException('ارسال پیامک برای این حساب موقتاً متوقف شده است.');if(!$security->daily_count_date||!$security->daily_count_date->isToday()){$security->daily_sent_count=0;$security->daily_count_date=now()->toDateString();$security->save();}if($security->last_sent_at&&now()->lt($security->last_sent_at->copy()->addSeconds(self::RESEND_SECONDS)))throw new RuntimeException('لطفاً '.now()->diffInSeconds($security->last_sent_at->copy()->addSeconds(self::RESEND_SECONDS)).' ثانیه دیگر صبر کنید.');$limit=match($security->restriction_level){0=>self::DAILY_LIMIT_NORMAL,1=>self::DAILY_LIMIT_RESTRICTED,default=>self::DAILY_LIMIT_SEVERE};if($security->daily_sent_count>=$limit)throw new RuntimeException('سقف ارسال پیامک امروز برای شما تکمیل شده است.');$lock=Cache::lock('otp-send:'.$phone,5);if(!$lock->get())throw new RuntimeException('درخواست دیگری در حال پردازش است. لطفاً کمی صبر کنید.');try{$code=(string)random_int(100000,999999);Cache::put('otp:code:'.$phone,hash('sha256',$code),self::EXPIRE_SECONDS);Cache::put('otp:expires:'.$phone,now()->addSeconds(self::EXPIRE_SECONDS)->timestamp,self::EXPIRE_SECONDS);$sent=$this->sms->sendOtp($phone,$code);if(!$sent){Cache::forget('otp:code:'.$phone);Cache::forget('otp:expires:'.$phone);$this->event($phone,'failed');throw new RuntimeException('ارسال پیامک انجام نشد.');}$security->last_sent_at=now();$security->daily_sent_count++;$security->last_ip=request()->ip();$security->save();$this->event($phone,'sent');return true;}finally{optional($lock)->release();}}
 public function verify(string $phone,string $code):bool{$phone=$this->phoneValidator->normalize($phone);if(!$this->phoneValidator->isValid($phone))return false;$stored=Cache::get('otp:code:'.$phone);if(!$stored){$this->event($phone,'expired');return false;}$hash=hash('sha256',trim($code));if(!hash_equals($stored,$hash)){$this->event($phone,'failed');return false;}Cache::forget('otp:code:'.$phone);Cache::forget('otp:expires:'.$phone);$this->event($phone,'verified');return true;}
 public function sendPasswordResetOtp(string $phone):bool{return $this->send($phone);}public function verifyPasswordResetOtp(string $phone,string $code):bool{return $this->verify($phone,$code);}
 private function event(string $phone,string $event):void{try{OtpEvent::create(['phone'=>$phone,'event'=>$event,'channel'=>'sms','ip'=>request()->ip()]);}catch(\Throwable $e){} }
}