@extends('admin.layout')
@section('title','کدهای تخفیف')
@section('content')
<div class="admin-page discount-page"><div class="admin-page-head"><div><div class="admin-eyebrow">رشد فروش</div><h1>کدهای تخفیف</h1><p>کد عمومی یا پیشنهاد اختصاصی بر اساس رفتار مشتری.</p></div><a href="{{ route('admin.discounts.create') }}" class="admin-primary-btn">ایجاد کد عمومی</a></div>@if(session('success'))<div class="admin-alert success">{{ session('success') }}</div>@endif
<section class="ai-offer"><div><span>پیشنهاد هوشمند مشتری</span><h2>برای مشتری مناسب، کد اختصاصی بسازید</h2><p>سیستم بر اساس سابقه خرید و امتیاز باشگاه، یک پیشنهاد محدود و شخصی ایجاد می‌کند و آن را در اعلان‌های مشتری ثبت می‌کند.</p></div><form method="POST" action="{{ route('admin.discounts.ai',$customers->first()?->id ?? 0) }}" id="aiOfferForm">@csrf<select id="customerSelect"><option value="">انتخاب مشتری</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ trim($customer->first_name.' '.$customer->last_name) }} · {{ $customer->phone }}</option>@endforeach</select><button type="button" id="aiOfferBtn">ساخت پیشنهاد AI</button></form></section>
<div class="admin-table-card"><div class="admin-table-head"><h2>کدهای موجود</h2></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>کد</th><th>مقدار</th><th>مخاطب</th><th>انقضا</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>@forelse($codes as $code)<tr><td><strong>{{ $code->code }}</strong>@if($code->ai_generated)<small class="ai-tag">AI</small>@endif</td><td>{{ rtrim(rtrim(number_format($code->amount,2),'0'),'.') }} {{ $code->is_percent?'%':'تومان' }}</td><td>{{ $code->targetUser?->first_name ? trim($code->targetUser->first_name.' '.$code->targetUser->last_name) : 'عمومی' }}</td><td>{{ $code->expires_at?->format('Y/m/d H:i') ?? 'بدون انقضا' }}</td><td>{{ $code->is_active?'فعال':'غیرفعال' }}</td><td><div class="admin-actions"><a href="{{ route('admin.discounts.edit',$code) }}">ویرایش</a><form method="POST" action="{{ route('admin.discounts.toggle',$code) }}">@csrf @method('PATCH')<button type="submit">{{ $code->is_active?'غیرفعال':'فعال' }}</button></form></div></td></tr>@empty<tr><td colspan="6">هنوز کدی ایجاد نشده است.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
@push('styles')<style>.discount-page{max-width:1200px;margin:auto;padding:28px}.ai-offer{margin:18px 0;padding:22px;border-radius:20px;background:linear-gradient(135deg,#111827,#312e5b);color:#fff;display:flex;justify-content:space-between;gap:20px;align-items:center}.ai-offer span{font-size:10px;color:#c4b5fd}.ai-offer h2{margin:4px 0;font-size:18px}.ai-offer p{font-size:11px;color:#d1d5db;max-width:650px;line-height:1.9}.ai-offer form{display:flex;gap:8px;min-width:300px}.ai-offer select{flex:1;border:0;border-radius:10px;padding:10px;font:inherit;font-size:11px}.ai-offer button{border:0;border-radius:10px;padding:10px 12px;background:#a855f7;color:#fff;font:inherit;font-weight:800;cursor:pointer}.ai-tag{margin-right:5px;padding:3px 5px;border-radius:5px;background:#f3e8ff;color:#7e22ce;font-size:9px}@media(max-width:800px){.ai-offer{display:block}.ai-offer form{margin-top:12px;min-width:0}}
</style>@endpush
@push('scripts')<script>document.getElementById('aiOfferBtn')?.addEventListener('click',function(){const id=document.getElementById('customerSelect').value;if(!id){alert('ابتدا مشتری را انتخاب کنید.');return}const form=document.getElementById('aiOfferForm');form.action='{{ url('/admin/discounts/ai') }}/'+id;form.submit()})</script>@endpush
