@extends('admin.layout')
@section('title','اتصال‌ها و سرویس‌ها')
@section('content')
<div class="admin-page integrations-page"><div class="admin-page-head"><div><div class="admin-eyebrow">تنظیمات سیستم</div><h1>اتصال‌ها و سرویس‌ها</h1><p>اطلاعات سرویس‌های خارجی را از این بخش مدیریت کنید؛ اطلاعات حساس در دیتابیس رمزگذاری می‌شوند.</p></div></div>
@if(session('success'))<div class="admin-alert success">{{ session('success') }}</div>@endif @if($errors->any())<div class="admin-alert error">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('admin.integrations.update') }}">@csrf @method('PUT')
<section class="admin-form-card integration-card"><div class="section-title"><b>✉</b><div><h2>ایمیل اختصاصی سایت</h2><p>برای تأیید ایمیل، پیشنهادهای محصول و خبرنامه از SMTP ایمیل دامنه خودتان استفاده کنید.</p></div></div><label class="switch-line"><input type="checkbox" name="mail[enabled]" value="1" @checked($mail['enabled'])><span>ارسال ایمیل سایت فعال باشد</span></label><div class="integration-grid"><label>SMTP Host<input name="mail[host]" value="{{ $mail['host'] }}" placeholder="mail.example.ir" dir="ltr"></label><label>Port<input name="mail[port]" type="number" value="{{ $mail['port'] }}" dir="ltr"></label><label>نام کاربری SMTP<input name="mail[username]" value="{{ $mail['username'] }}" placeholder="noreply@example.ir" dir="ltr"></label><label>رمز SMTP<input name="mail[password]" type="password" placeholder="برای تغییر، رمز جدید را وارد کنید" dir="ltr" autocomplete="new-password"></label><label>رمزنگاری<select name="mail[encryption]"><option value="tls" @selected($mail['encryption']==='tls')>TLS</option><option value="ssl" @selected($mail['encryption']==='ssl')>SSL</option><option value="none" @selected($mail['encryption']==='none')>بدون رمزنگاری</option></select></label><label>آدرس ارسال‌کننده<input name="mail[from_address"] value="{{ $mail['from_address'] }}" placeholder="noreply@example.ir" dir="ltr"></label><label>نام ارسال‌کننده<input name="mail[from_name]" value="{{ $mail['from_name'] }}"></label></div><button class="admin-primary-btn" type="submit">ذخیره تنظیمات ایمیل</button></section>
<section class="admin-form-card integration-card"><div class="section-title"><b>G</b><div><h2>ورود با حساب گوگل</h2><p>فعلاً در سایت نمایش داده نمی‌شود. بعد از دریافت Client ID و Client Secret، اطلاعات را اینجا ثبت می‌کنید.</p></div></div><div class="integration-grid"><label class="switch-line"><input type="checkbox" name="google[enabled]" value="1" @checked($google['enabled'])><span>فعال‌سازی ورود گوگل</span></label><label>Client ID<input name="google[client_id]" value="{{ $google['client_id'] }}" dir="ltr"></label><label>Client Secret<input name="google[client_secret]" type="password" placeholder="برای تغییر، مقدار جدید را وارد کنید" dir="ltr" autocomplete="new-password"></label></div><div class="integration-note">تا زمانی که OAuth کامل فعال نشده است، دکمه ورود گوگل در سایت نمایش داده نمی‌شود.</div><button class="admin-primary-btn" type="submit">ذخیره اطلاعات گوگل</button></section>
</form>
<section class="admin-form-card integration-card"><div class="section-title"><b>✓</b><div><h2>آزمایش ایمیل</h2><p>بعد از ذخیره تنظیمات، یک پیام آزمایشی به ایمیل موردنظر ارسال کنید.</p></div></div><form method="POST" action="{{ route('admin.integrations.test-mail') }}" class="integration-test">@csrf<input type="email" name="email" placeholder="ایمیل دریافت‌کننده آزمایش" dir="ltr" required><button type="submit" class="admin-secondary-btn">ارسال آزمایشی</button></form></section></div>
@endsection
@push('styles')<style>.integration-card{margin-bottom:16px}.integration-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.integration-grid label{display:grid;gap:7px;font-size:11px;font-weight:800;color:#475467}.integration-grid input,.integration-grid select{height:44px;border:1px solid #dfe3ea;border-radius:11px;padding:0 11px;font:inherit;background:#fff}.switch-line{display:flex!important;align-items:center;gap:9px;margin-bottom:15px}.switch-line input{width:18px;height:18px}.integration-note{margin-top:15px;margin-bottom:12px;padding:12px;border-radius:11px;background:#f8f9ff;color:#667085;font-size:10px;line-height:1.9}.integration-test{display:flex;gap:8px}.integration-test input{flex:1;height:44px;border:1px solid #dfe3ea;border-radius:11px;padding:0 11px;font:inherit}.admin-primary-btn,.admin-secondary-btn{cursor:pointer}@media(max-width:650px){.integration-grid{grid-template-columns:1fr}.integration-test{display:grid}}</style>@endpush