@extends('admin.layout')
@section('title','مرکز هوش مصنوعی')
@section('content')
<div class="admin-page ai-dashboard"><div class="admin-page-head"><div><div class="admin-eyebrow">AI COMMERCE · CONTROL CENTER</div><h1>مرکز هوش مصنوعی</h1><p>وضعیت بررسی محصول، شواهد و بازخورد کاربران را از یک نقطه مدیریت کنید.</p></div></div>
<div class="stats">@foreach([['pending','در انتظار بررسی'],['approved','تأییدشده'],['flagged','نیازمند اصلاح'],['reviews','نظرات منتشرشده']] as $s)<div class="stat"><small>{{ $s[1] }}</small><strong>{{ number_format($stats[$s[0]]) }}</strong></div>@endforeach</div>
<div class="notice"><strong>Provider فعلاً متصل نیست.</strong><span>سیستم عمداً هیچ خلاصه، ادعا یا پیشنهاد ساختگی تولید نمی‌کند. پس از انتخاب Provider، تحلیل فایل و دانش محصول به همین داشبورد متصل خواهد شد.</span></div>
<section class="admin-form-card"><div class="head"><h2>آخرین تحلیل‌ها</h2><span>Evidence-first</span></div>@forelse($recent as $row)<div class="analysis"><div><b>{{ $row->product?->title ?: 'محصول حذف‌شده' }}</b><small>{{ $row->status }} · {{ $row->inspected_at?->format('Y/m/d H:i') ?: '—' }}</small></div><strong>{{ $row->score !== null ? $row->score.'/100' : '—' }}</strong></div>@empty<p class="empty">هنوز تحلیل واقعی ثبت نشده است.</p>@endforelse</section></div>
@endsection
@push('styles')<style>.ai-dashboard{max-width:1100px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.stat{padding:17px;background:#fff;border:1px solid #eaecf0;border-radius:15px}.stat small,.stat strong{display:block}.stat small{font-size:10px;color:#667085}.stat strong{font-size:25px;margin-top:7px}.notice{display:flex;flex-direction:column;gap:4px;padding:15px 17px;border:1px solid #dfe4ff;background:#f8f9ff;border-radius:15px;margin-bottom:18px}.notice strong{font-size:12px}.notice span{font-size:10px;color:#667085;line-height:1.8}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.head h2{margin:0;font-size:16px}.head span{font-size:10px;color:#4f46e5}.analysis{display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-top:1px solid #edf0f4}.analysis b,.analysis small{display:block}.analysis b{font-size:11px}.analysis small{font-size:10px;color:#98a2b3;margin-top:3px}.analysis>strong{font-size:12px}.empty{font-size:11px;color:#98a2b3}@media(max-width:700px){.stats{grid-template-columns:1fr 1fr}}</style>@endpush
