@extends('account.layout')
@section('title','تنظیمات هوش مصنوعی')
@section('content')
<div class="admin-module-page"><div class="admin-module-head"><div><span class="admin-kicker">مرکز هوش مصنوعی</span><h1>تنظیمات اتصال هوش مصنوعی</h1><p>کلیدها رمزنگاری می‌شوند و برای حفظ امنیت دوباره نمایش داده نمی‌شوند.</p></div></div>
@if(session('success'))<div class="settings-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="settings-errors">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form method="POST" action="{{ route('admin.ai.settings.update') }}" class="admin-module-card ai-settings-form">@csrf
<div class="form-grid"><label>ارائه‌دهنده اصلی<select name="provider"><option value="gemini" @selected(($settings['provider']??'gemini')==='gemini')>Google Gemini</option></select></label><label>مهلت پاسخ (ثانیه)<input type="number" name="timeout" min="5" max="120" value="{{ $settings['timeout']??30 }}"></label><label class="full">کلید Gemini 2.5<input type="password" name="gemini_key" autocomplete="new-password" placeholder="برای تغییر، کلید جدید را وارد کنید"></label><label>ارائه‌دهنده پشتیبان<select name="fallback_provider"><option value="gapgpt" @selected(($settings['fallback_provider']??'gapgpt')==='gapgpt')>گپ‌جی‌پی‌تی</option></select></label><label>مدل پشتیبان<input type="text" name="fallback_model" value="{{ $settings['fallback_model']??'gpt-4o-mini' }}"></label><label class="full">کلید گپ‌جی‌پی‌تی<input type="password" name="fallback_key" autocomplete="new-password" placeholder="برای تغییر، کلید جدید را وارد کنید"></label><label class="full">نشانی رابط پشتیبان<input type="url" name="fallback_endpoint" value="{{ $settings['fallback_endpoint']??'https://api.gapgpt.app/v1' }}"></label></div><div class="settings-note"><x-icon name="warning" size="18"/><span>مسیر اجرا: جست‌وجوی شواهد واقعی محصولات ← Gemini ← در صورت خطا سرویس پشتیبان ← در نبود هر دو، ادامه عادی فروشگاه بدون وابستگی به AI.</span></div><button class="ds-btn ds-btn-primary" type="submit">ذخیره تنظیمات</button></form></div>
@endsection
@push('styles')<style>.ai-settings-form{max-width:1000px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.form-grid label{display:grid;gap:7px;font-weight:800;font-size:13px;color:#475467}.form-grid label.full{grid-column:1/-1}.form-grid input,.form-grid select{height:44px;border:1px solid #e1e5ec;border-radius:11px;padding:0 12px;font:inherit;background:#fff}.settings-note{margin:20px 0;padding:14px;border-radius:13px;background:#fff9e8;color:#795b16;display:flex;gap:9px;align-items:flex-start;font-size:12px;line-height:1.9}.settings-success,.settings-errors{max-width:1000px;margin:0 0 14px;padding:12px 14px;border-radius:11px;font-size:12px}.settings-success{background:#ecfdf3;color:#027a48}.settings-errors{background:#fff0f0;color:#b42318}@media(max-width:650px){.form-grid{grid-template-columns:1fr}.form-grid label.full{grid-column:auto}}</style>@endpush
