@extends('admin.layout')
@section('content')
<div class="admin-content ds-editor-page">
<header class="pc3-head"><div><span>مدیریت محتوای سایت</span><h1>{{ $page->title }}</h1><p>محتوای صفحه را با ویرایشگر ساختاریافته، تیتر، فهرست، جدول، تصویر و پیوند مدیریت کنید.</p></div><a class="btn" href="{{ route('admin.content.index') }}">بازگشت به صفحات</a></header>
@if($errors->any())<div class="pc3-alert">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form class="editor-card" method="POST" action="{{ route('admin.content.update',$page) }}">@csrf @method('PUT')
<section class="pc3-card"><div class="pc3-title"><b>۱</b><div><h2>اطلاعات صفحه</h2><p>عنوان اصلی و اطلاعات سئو را در این بخش تنظیم کنید.</p></div></div><div class="pc3-grid"><label>عنوان صفحه<input name="title" value="{{ old('title',$page->title) }}" maxlength="255" required></label><label>عنوان SEO<input name="meta_title" value="{{ old('meta_title',$page->meta_title) }}" maxlength="255"></label><label class="pc3-full">توضیحات SEO<textarea name="meta_description" rows="3" maxlength="320">{{ old('meta_description',$page->meta_description) }}</textarea></label></div></section>
<section class="pc3-card"><div class="pc3-title"><b>۲</b><div><h2>محتوای اصلی</h2><p>محتوا را مانند یک صفحه حرفه‌ای وب بسازید؛ متن ساده دیگر تنها گزینه نیست.</p></div></div><div class="ds-rich-editor" data-editor><div class="ds-editor-toolbar" role="toolbar" aria-label="ویرایشگر محتوای صفحه"><select data-cmd="formatBlock" aria-label="نوع متن"><option value="P">پاراگراف</option><option value="H1">عنوان ۱</option><option value="H2">عنوان ۲</option><option value="H3">عنوان ۳</option></select><button type="button" data-cmd="bold"><b>B</b></button><button type="button" data-cmd="italic"><i>I</i></button><button type="button" data-cmd="underline"><u>U</u></button><button type="button" data-cmd="strikeThrough">خط‌خورده</button><button type="button" data-cmd="justifyRight">راست</button><button type="button" data-cmd="justifyCenter">وسط</button><button type="button" data-cmd="justifyLeft">چپ</button><button type="button" data-cmd="insertUnorderedList">• فهرست</button><button type="button" data-cmd="insertOrderedList">۱. فهرست</button><button type="button" data-cmd="blockquote">نقل‌قول</button><button type="button" data-cmd="createLink">پیوند</button><button type="button" data-cmd="insertImage">تصویر</button><button type="button" data-cmd="insertMedia">رسانه</button><button type="button" data-cmd="insertTable">جدول</button><button type="button" data-cmd="foreColor">رنگ متن</button><button type="button" data-cmd="hiliteColor">رنگ زمینه</button><button type="button" data-cmd="removeFormat">پاک‌سازی</button></div><div class="ds-editor-content" contenteditable="true" spellcheck="true">{!! old('content',$page->content) !!}</div><textarea class="ds-editor-value" name="content" hidden></textarea></div></section>
<section class="pc3-card ds-editor-help"><div><strong>ساختار پیشنهادی محتوا</strong><p>برای صفحات مهم از یک مقدمه کوتاه، تیترهای H2/H3، پاراگراف‌های کوتاه، فهرست‌ها، جدول در صورت نیاز و لینک داخلی استفاده کنید.</p></div></section>
<label class="publish-row"><input type="checkbox" name="is_published" value="1" @checked(old('is_published',$page->is_published))> انتشار صفحه</label><button class="ds-save" type="submit">ذخیره صفحه</button>
</form></div>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('css/product-editor.css') }}"><style>.ds-editor-page{padding:24px}.ds-editor-page .editor-card{max-width:1120px}.ds-editor-help{display:flex;align-items:center;background:#f8faff}.ds-editor-help strong{font-size:13px;color:#1d2939}.ds-editor-help p{margin:6px 0 0;color:#667085;font-size:11px;line-height:2}.publish-row{display:flex!important;align-items:center;gap:8px;font-size:12px;font-weight:800;margin:14px 0}.publish-row input{width:17px;height:17px}.ds-save{border:0;border-radius:12px;background:#101828;color:#fff;padding:13px 20px;font:inherit;font-weight:900;cursor:pointer}@media(max-width:700px){.ds-editor-page{padding:14px}}</style>@endpush
@push('scripts')<script src="{{ asset('js/product-editor.js') }}" defer></script>@endpush
