@extends('admin.layout')
@section('title','افزودن Storage')
@section('content')
<div class="admin-page narrow"><div class="admin-page-head"><div><div class="admin-eyebrow">Storage Management</div><h1>افزودن محل ذخیره‌سازی</h1><p>هر Provider فقط برای یک بخش و یک موقعیت ثبت می‌شود و اولویت آن مسیر انتخاب خودکار را تعیین می‌کند.</p></div></div>
@if($errors->any())<div class="admin-alert error">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<div class="admin-form-card"><form method="POST" action="{{ route('admin.storage.store') }}" class="admin-form">@csrf
<div class="form-row"><div class="form-group"><label>نام Provider</label><input name="name" value="{{ old('name') }}" placeholder="فضای ابری اصلی" required></div><div class="form-group"><label>نوع اتصال</label><select name="type" id="storage-type"><option value="local">سرور داخلی (Local)</option><option value="api" @selected(old('type')==='api')>API</option></select></div></div>
<div class="form-row"><div class="form-group"><label>بخش ذخیره‌سازی</label><select name="scope" required>@foreach($scopes as $key=>$label)<option value="{{ $key }}" @selected(old('scope','files')===$key)>{{ $label }}</option>@endforeach</select></div><div class="form-group"><label>موقعیت</label><select name="location" required>@foreach($locations as $key=>$label)<option value="{{ $key }}" @selected(old('location','external')===$key)>{{ $label }}</option>@endforeach</select></div></div>
<div class="form-group"><label>اولویت <small>(اجباری)</small></label><input type="number" name="priority" value="{{ old('priority',100) }}" min="1" max="999999" required><small>عدد کمتر = اولویت بالاتر. در صورت چند Provider فعال، سیستم از اولویت برای انتخاب مسیر استفاده می‌کند.</small></div>
<div class="form-group"><label>لینک مستندات API <small>(اختیاری)</small></label><input type="url" name="documentation_url" value="{{ old('documentation_url') }}" dir="ltr" placeholder="https://..."></div>
<div id="api-fields" hidden>
<div class="admin-alert info">برای API فقط <strong>API Key</strong> و <strong>اولویت</strong> اجباری‌اند. اگر Endpoint و مستندات سرویس را وارد نکنید، در زمان اتصال باید مشخصات API را از شما دریافت کنیم.</div>
<div class="form-group"><label>API Key <small>(اجباری)</small></label><input type="password" name="api_key" dir="ltr" autocomplete="new-password"></div>
<div class="form-group"><label>Endpoint اصلی <small>(اختیاری)</small></label><input type="url" name="endpoint" value="{{ old('endpoint') }}" dir="ltr" placeholder="https://example.com/api"></div>
<div class="form-row"><div class="form-group"><label>سقف کل فضا GB</label><input type="number" name="limit_gb" min="0" step="0.01" value="{{ old('limit_gb',0) }}"></div><div class="form-group"><label>حداکثر حجم هر فایل MB</label><input type="number" name="max_file_mb" min="0" step="0.01" value="{{ old('max_file_mb',0) }}"></div></div>
<div class="form-row"><div class="form-group"><label>حداکثر تعداد فایل</label><input type="number" name="max_files" min="0" value="{{ old('max_files',0) }}"></div><div class="form-group"><label>مدت نگهداری فایل موقت (روز)</label><input type="number" name="retention_days" min="1" value="{{ old('retention_days',30) }}"></div></div>
<div class="form-row"><div class="form-group"><label>Upload path</label><input name="upload_path" value="{{ old('upload_path','upload') }}" dir="ltr"></div><div class="form-group"><label>Delete path</label><input name="delete_path" value="{{ old('delete_path','delete') }}" dir="ltr"></div></div>
<div class="form-row"><div class="form-group"><label>Exists path</label><input name="exists_path" value="{{ old('exists_path','exists') }}" dir="ltr"></div><div class="form-group"><label>Download path</label><input name="download_path" value="{{ old('download_path','download') }}" dir="ltr"></div></div>
<div class="form-row"><div class="form-group"><label>Test path</label><input name="test_path" value="{{ old('test_path') }}" dir="ltr"></div><div class="form-group"><label>File field</label><input name="file_field" value="{{ old('file_field','file') }}" dir="ltr"></div></div>
<div class="form-row"><div class="form-group"><label>Path field</label><input name="path_field" value="{{ old('path_field','path') }}" dir="ltr"></div><div class="form-group"><label>Header name</label><input name="header_name" value="{{ old('header_name','Authorization') }}" dir="ltr"></div></div>
<div class="form-group"><label>Header prefix</label><input name="header_prefix" value="{{ old('header_prefix','Bearer ') }}" dir="ltr"></div>
</div>
<div class="form-actions"><a href="{{ route('admin.storage.index') }}" class="admin-secondary-btn">انصراف</a><button type="submit" class="admin-primary-btn">ذخیره Provider</button></div>
</form></div></div>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const t=document.getElementById('storage-type'),f=document.getElementById('api-fields');const sync=()=>f.hidden=t.value!=='api';t.addEventListener('change',sync);sync();});</script>@endpush