@extends('admin.layout')
@section('title','مدیریت ذخیره‌سازی')
@section('content')
<div class="admin-page"><div class="admin-page-head"><div><div class="admin-eyebrow">Storage Architecture</div><h1>ذخیره‌سازی</h1><p>هشت مسیر مستقل برای فایل‌ها، بکاپ‌ها، اطلاعات کاربران و فایل‌های موقت؛ هرکدام با سرور داخلی و خارجی.</p></div><div class="admin-actions"><a href="{{ route('admin.files.index') }}" class="admin-secondary-btn">کتابخانه فایل‌ها</a><a href="{{ route('admin.storage.create') }}" class="admin-primary-btn">+ افزودن Provider</a></div></div>
@if(session('success'))<div class="admin-alert success">{{ session('success') }}</div>@endif @if(session('error'))<div class="admin-alert error">{{ session('error') }}</div>@endif
<div class="storage-lanes">
@foreach($groups as $scope=>$locations)
<section class="storage-lane"><div class="storage-lane-title"><div><span class="storage-lane-kicker">{{ str_pad((string)(array_search($scope,array_keys($groups))+1),2,'0',STR_PAD_LEFT) }}</span><h2>{{ \App\Models\StorageProvider::SCOPES[$scope] }}</h2></div><a href="{{ route('admin.storage.create') }}?scope={{ $scope }}" class="action-btn edit">+ Provider</a></div>
<div class="storage-two-columns">
@foreach($locations as $location=>$items)<div class="storage-location"><div class="storage-location-head"><strong>{{ \App\Models\StorageProvider::LOCATIONS[$location] }}</strong><span>{{ $items->count() }} Provider</span></div>
@forelse($items as $provider)@php($c=$provider->capacity)<article class="storage-provider-card"><div class="storage-provider-head"><div><strong>{{ $provider->name }}</strong><small>{{ strtoupper($provider->type) }} · اولویت {{ $provider->priority }}</small></div>@if($provider->is_default)<span class="status-badge active">پیش‌فرض</span>@endif</div><div class="storage-progress"><span style="width:{{ $c['percent'] }}%"></span></div><div class="storage-stats">@if($c['total'])<span>{{ number_format($c['used']/1073741824,2) }} GB مصرف</span><span>{{ number_format($c['free']/1073741824,2) }} GB آزاد</span><span>{{ $c['percent'] }}٪</span>@else<span>ظرفیت نامحدود/نامشخص</span>@endif</div><div class="storage-provider-actions"><form method="POST" action="{{ route('admin.storage.test',$provider) }}">@csrf<button class="action-btn toggle">تست</button></form><a href="{{ route('admin.storage.edit',$provider) }}" class="action-btn edit">تنظیمات</a>@if(!$provider->is_default)<form method="POST" action="{{ route('admin.storage.default',$provider) }}">@csrf @method('PATCH')<button class="action-btn edit">پیش‌فرض</button></form>@endif</div></article>@empty<div class="storage-empty">Provider برای این مسیر ثبت نشده است.</div>@endforelse
</div>@endforeach</div></section>
@endforeach
</div></div>
@endsection
@push('styles')<style>.storage-lanes{display:grid;gap:18px}.storage-lane{border:1px solid #e8edf3;border-radius:18px;background:#fff;padding:18px}.storage-lane-title,.storage-location-head,.storage-provider-head,.storage-stats,.storage-provider-actions{display:flex;align-items:center;justify-content:space-between;gap:10px}.storage-lane-title{margin-bottom:16px}.storage-lane-title h2{margin:4px 0 0}.storage-lane-kicker{font-size:11px;color:#667085}.storage-two-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.storage-location{border:1px solid #edf0f4;border-radius:14px;padding:14px;background:#fafbfc}.storage-location-head{font-size:13px;margin-bottom:10px}.storage-location-head span,.storage-provider-head small{color:#98a2b3;font-size:11px}.storage-provider-card{background:#fff;border:1px solid #e7ebf0;border-radius:12px;padding:12px;margin-top:9px}.storage-provider-head{align-items:flex-start}.storage-progress{height:8px;background:#edf1f5;border-radius:20px;overflow:hidden;margin:12px 0 7px}.storage-progress span{display:block;height:100%;background:linear-gradient(90deg,#4f46e5,#7c3aed);border-radius:20px;transition:width .4s ease}.storage-stats{font-size:11px;color:#667085}.storage-provider-actions{justify-content:flex-start;margin-top:11px}.storage-empty{padding:18px;text-align:center;color:#98a2b3;font-size:12px;background:#fff;border-radius:10px}.storage-provider-card form{margin:0}@media(max-width:800px){.storage-two-columns{grid-template-columns:1fr}}</style>@endpush