@extends('admin.layout')
@section('title','Storage')
@section('content')
<div class="admin-page"><div class="admin-page-head"><div><div class="admin-eyebrow">Storage Management</div><h1>فضای ذخیره‌سازی</h1><p>مدیریت چند Storage، ظرفیت و محل ذخیره فایل‌های محصولات</p></div><div class="admin-actions"><a href="{{ route('admin.files.index') }}" class="admin-secondary-btn">کتابخانه فایل‌ها</a><a href="{{ route('admin.storage.create') }}" class="admin-primary-btn">+ افزودن Provider</a></div></div>
@if(session('success'))<div class="admin-alert success">{{ session('success') }}</div>@endif @if(session('error'))<div class="admin-alert error">{{ session('error') }}</div>@endif
<div class="storage-provider-grid">
@forelse($providers as $provider)
@php($c=$provider->capacity)
<div class="admin-box storage-provider-card"><div class="admin-box-head"><div><span class="muted">{{ strtoupper($provider->type) }}</span><h2>{{ $provider->name }}</h2></div><div>@if($provider->is_default)<span class="status-badge active">پیش‌فرض</span>@endif</div></div>
<div class="storage-meta"><span>{{ $provider->products_count }} محصول</span><span>@if($provider->is_active) فعال @else غیرفعال @endif</span></div>
<div class="storage-capacity"><div class="storage-capacity-head"><strong>ظرفیت</strong><span>@if($c['total']) {{ number_format($c['used']/1073741824,2) }} / {{ number_format($c['total']/1073741824,2) }} GB @else بدون سقف ثبت‌شده @endif</span></div><div class="storage-progress"><span style="width:{{ $c['percent'] }}%"></span></div><small>@if($c['total']) {{ $c['percent'] }}٪ استفاده شده — {{ number_format($c['free']/1073741824,2) }} GB آزاد @else ظرفیت واقعی توسط API ارائه نشده است @endif</small></div>
<div class="admin-actions"><form method="POST" action="{{ route('admin.storage.test',$provider) }}">@csrf<button class="action-btn toggle" type="submit">تست اتصال</button></form>@if(!$provider->is_default)<form method="POST" action="{{ route('admin.storage.default',$provider) }}">@csrf @method('PATCH')<button class="action-btn edit" type="submit">پیش‌فرض</button></form>@endif<a href="{{ route('admin.storage.edit',$provider) }}" class="action-btn edit">تنظیمات</a></div></div>
@empty<div class="admin-box"><div class="admin-empty">هنوز Storage Provider ثبت نشده است.</div></div>@endforelse
</div></div>
@endsection
@push('styles')<style>.storage-provider-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px}.storage-provider-card{margin:0}.storage-meta{display:flex;justify-content:space-between;color:#667085;font-size:12px;padding:10px 0}.storage-capacity{margin:8px 0 16px}.storage-capacity-head{display:flex;justify-content:space-between;font-size:12px;margin-bottom:8px}.storage-progress{height:9px;background:#edf1f5;border-radius:20px;overflow:hidden}.storage-progress span{display:block;height:100%;background:linear-gradient(90deg,#4f46e5,#7c3aed);border-radius:20px;transition:width .4s ease}.storage-capacity small{display:block;color:#98a2b3;margin-top:7px}</style>@endpush