@extends('admin.layout')
@section('title','ویرایش کاربر')
@section('content')
@php($primaryDefault=in_array($user->role,$roles->pluck('name')->all(),true)?$user->role:'buyer')
@php($selectedRolesDefault=$user->roles->pluck('name')->all()?:[$primaryDefault])
<div class="account-head"><div><small>مدیریت کاربران</small><h1>دسترسی و مشخصات کاربر</h1><p>{{ $user->phone }} · نقش‌ها می‌توانند همزمان فعال باشند.</p></div></div>
<section class="account-card access-editor"><form method="POST" action="{{ route('admin.users.update',$user) }}" class="account-form">@csrf @method('PUT')
<div class="form-grid"><label>نام<input type="text" name="first_name" value="{{ old('first_name',$user->first_name) }}" required></label><label>نام خانوادگی<input type="text" name="last_name" value="{{ old('last_name',$user->last_name) }}"></label><label>شماره موبایل<input type="tel" name="phone" value="{{ old('phone',$user->phone) }}" dir="ltr" required></label><label>نقش اصلی<select name="primary_role" required>@foreach($roles as $role)<option value="{{ $role->name }}" @selected(old('primary_role',$primaryDefault)===$role->name)>{{ $role->label }} ({{ $role->name }})</option>@endforeach</select></label></div>
<div class="access-title"><div><h2>سطح دسترسی</h2><small>یک کاربر می‌تواند خریدار، فروشنده یا مدیر باشد و نقش‌ها روی هم اعمال می‌شوند.</small></div></div><div class="role-choice-grid">@php($selectedRoles=old('roles',$selectedRolesDefault))@foreach($roles as $role)<label class="role-choice"><input type="checkbox" name="roles[]" value="{{ $role->name }}" @checked(in_array($role->name,$selectedRoles,true))><span><b>{{ $role->label }}</b><small>{{ $role->description ?: 'بدون توضیح' }}</small></span></label>@endforeach</div>
<div class="permission-preview"><strong>مجوزهای نقش‌های انتخاب‌شده</strong><div class="permission-tags">@foreach($roles->whereIn('name',$selectedRoles) as $role)@foreach($role->permissions as $permission)<span>{{ $permission->label }}</span>@endforeach @endforeach</div></div>
<div class="form-grid"><label>رمز عبور جدید<input type="password" name="password" minlength="8" autocomplete="new-password"></label><label>تکرار رمز عبور<input type="password" name="password_confirmation" minlength="8" autocomplete="new-password"></label></div>
<div class="form-note">وضعیت حساب: <strong>{{ $user->is_active?'فعال':'غیرفعال' }}</strong> · موبایل: <strong>{{ $user->phone_verified_at?'تأیید شده':'تأیید نشده' }}</strong></div><div class="form-actions"><a href="{{ route('admin.users.index') }}" class="btn">بازگشت</a><button type="submit" class="btn primary">ذخیره دسترسی‌ها</button></div></form></section>
@endsection
@push('styles')<style>.access-editor{max-width:1000px}.access-title{margin-top:25px;padding-top:20px;border-top:1px solid #edf0f4}.access-title h2{font-size:16px;margin:0}.access-title small{font-size:9px;color:#98a2b3}.role-choice-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.role-choice{display:flex;align-items:flex-start;gap:9px;padding:13px;border:1px solid #e6e8ef;border-radius:13px;cursor:pointer;background:#fff;transition:.18s}.role-choice:has(input:checked){border-color:#c7d2fe;background:#f7f8ff;box-shadow:0 5px 18px rgba(48,74,202,.07)}.role-choice input{margin-top:3px}.role-choice b,.role-choice small{display:block}.role-choice b{font-size:10px}.role-choice small{font-size:8px;color:#98a2b3;margin-top:4px;line-height:1.8}.permission-preview{margin-top:16px;padding:14px;background:#f8fafc;border:1px solid #edf0f4;border-radius:13px}.permission-preview>strong{font-size:10px}.permission-tags{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.permission-tags span{padding:5px 7px;background:#eef1ff;color:#304aca;border-radius:7px;font-size:8px}@media(max-width:800px){.role-choice-grid{grid-template-columns:1fr}}</style>@endpush