@extends('admin.layout')
@section('title','تأیید محصولات')
@section('content')
<div class="approval-page">
<div class="approval-top"><div><h1>تأیید محصولات</h1><p>محصولات فروشندگان را پیش از انتشار بررسی کنید؛ محصول مدیر اصلی مستقیماً منتشر می‌شود.</p></div><nav><a class="{{ $status==='pending'?'active':'' }}" href="?status=pending">نیازمند بررسی</a><a class="{{ $status==='approved'?'active':'' }}" href="?status=approved">تأییدشده</a><a class="{{ $status==='all'?'active':'' }}" href="?status=all">همه</a></nav></div>
<div class="approval-list">
@forelse($products as $product)
<article class="approval-card"><div class="approval-main"><div class="approval-icon"><x-icon name="file" size="30" /></div><div><h2>{{ $product->title }}</h2><p>{{ $product->category?->name }} · {{ number_format($product->price) }} تومان</p><small>وضعیت: <b>{{ $product->approval_status }}</b></small></div></div><div class="approval-actions"><a href="{{ route('admin.products.edit',$product) }}">بررسی و ویرایش</a>@if($product->approval_status!=='approved')<form method="POST" action="{{ route('admin.products.approve',$product) }}">@csrf @method('PATCH')<button class="approve" type="submit">تأیید و انتشار</button></form><form method="POST" action="{{ route('admin.products.revision',$product) }}">@csrf @method('PATCH')<input name="approval_note" required placeholder="دلیل اصلاح را بنویسید"><button class="revise" type="submit">بازگشت برای اصلاح</button></form><form method="POST" action="{{ route('admin.products.reject',$product) }}">@csrf @method('PATCH')<input name="approval_note" required placeholder="دلیل رد"><button class="reject" type="submit">رد محصول</button></form>@endif</div></article>
@empty<div class="approval-empty"><x-icon name="check" size="34" /><h2>موردی برای بررسی نیست</h2><p>صف بررسی محصولات فعلاً خالی است.</p></div>@endforelse
</div>{{ $products->links() }}</div>
@endsection
@push('styles')<style>.approval-page{max-width:1200px;margin:auto;padding:28px}.approval-top{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:22px}.approval-top h1{margin:0}.approval-top p{color:#667085}.approval-top nav{display:flex;gap:6px;background:#f4f5f8;padding:5px;border-radius:12px}.approval-top nav a{padding:8px 12px;border-radius:9px;font-size:12px}.approval-top nav a.active{background:#fff;box-shadow:0 2px 8px #10182812}.approval-list{display:grid;gap:13px}.approval-card{background:#fff;border:1px solid #e6e8ee;border-radius:18px;padding:18px;display:flex;justify-content:space-between;gap:20px;align-items:center}.approval-main{display:flex;gap:14px;align-items:center}.approval-icon{width:52px;height:52px;border-radius:14px;background:#f0edff;color:#6541d8;display:grid;place-items:center}.approval-main h2{font-size:16px;margin:0}.approval-main p,.approval-main small{color:#667085;font-size:12px}.approval-actions{display:flex;align-items:center;gap:7px;flex-wrap:wrap;justify-content:end}.approval-actions a,.approval-actions button{border:0;border-radius:9px;padding:9px 11px;font:inherit;font-size:11px;cursor:pointer}.approval-actions a{background:#f3f4f6}.approve{background:#15945a;color:#fff}.revise{background:#fff4d6}.reject{background:#fff0f0;color:#c0392b}.approval-actions input{padding:9px;border:1px solid #ddd;border-radius:9px;width:160px;font:inherit;font-size:11px}.approval-empty{text-align:center;padding:60px;background:#fff;border:1px solid #eee;border-radius:18px;color:#667085}.approval-empty svg{color:#15945a}@media(max-width:800px){.approval-top,.approval-card{flex-direction:column;align-items:stretch}.approval-actions{justify-content:start}}
</style>@endpush
