@extends('admin.layout')
@section('title', 'افزودن محصول')
@section('content')
<div class="admin-page narrow ai-product-page">
    <div class="admin-page-head"><div><div class="admin-eyebrow">مدیریت محصولات · کنترل هوشمند</div><h1>افزودن محصول</h1><p>فایل، توضیحات و اطلاعات فروش را ثبت کنید؛ موارد مشکوک قبل از انتشار علامت می‌خورند.</p></div><a href="{{ route('admin.products.index') }}" class="admin-secondary-btn">بازگشت به محصولات</a></div>
    @if($errors->any())<div class="admin-alert error"><ul style="margin:0;padding-right:20px">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="ai-trust-banner"><div class="ai-trust-icon">✦</div><div><strong>بررسی هوشمند محصول</strong><span>مبنای بررسی محتوایی خود فایل است؛ متن فروشنده حقیقت قطعی نیست. ادعاهای اغراق‌آمیز و موارد مشکوک برای اصلاح یا بررسی مدیر علامت می‌خورند.</span></div></div>
    <section class="admin-form-card"><form method="POST" action="{{ route('admin.products.store') }}" enctype="multipart/form-data" class="admin-form">
        @csrf
        <div class="form-row"><div class="form-group"><label for="title">نام محصول</label><input id="title" type="text" name="title" value="{{ old('title') }}" required></div><div class="form-group"><label for="category_id">دسته‌بندی</label><select id="category_id" name="category_id" required><option value="">انتخاب دسته‌بندی</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id') == $category->id)>{{ $category->name }}</option>@endforeach</select></div></div>
        <div class="form-row"><div class="form-group"><label for="slug">Slug</label><input id="slug" type="text" name="slug" value="{{ old('slug') }}" placeholder="مثلاً photoshop-course" dir="ltr"><small>در صورت خالی بودن، سیستم آن را تولید می‌کند.</small></div><div class="form-group"><label for="price">قیمت</label><input id="price" type="number" name="price" value="{{ old('price', 0) }}" min="0" required><small>مبلغ به تومان</small></div></div>
        <div class="form-group"><label for="storage_provider_id">محل نگهداری فایل</label><select id="storage_provider_id" name="storage_provider_id" required><option value="">انتخاب Storage</option>@foreach($storageProviders as $provider)<option value="{{ $provider->id }}" @selected(old('storage_provider_id', $provider->is_default ? $provider->id : null) == $provider->id)>{{ $provider->name }} — {{ strtoupper($provider->type) }}</option>@endforeach</select></div>
        <div class="form-group"><label for="short_description">توضیح کوتاه</label><textarea id="short_description" name="short_description" rows="3">{{ old('short_description') }}</textarea><small>اطلاعات حدسی وارد نکنید؛ محتوای فایل مرجع اصلی خواهد بود.</small></div>
        <div class="form-group"><label for="description">توضیحات کامل محصول</label><textarea id="description" name="description" rows="10">{{ old('description') }}</textarea></div>
        <div class="ai-content-check"><div class="ai-check-title"><span>کنترل ادعاهای تبلیغاتی</span><b>فعال</b></div><p>عبارت‌هایی مانند «بهترین»، «تضمینی»، «صددرصد» و ادعاهای قابل‌اثبات باید با محتوای واقعی فایل سازگار باشند.</p></div>
        <div class="form-row"><div class="form-group"><label for="thumbnail">تصویر محصول</label><input id="thumbnail" type="file" name="thumbnail" accept=".jpg,.jpeg,.png,.webp"><small>JPG، PNG یا WEBP — حداکثر 5MB</small></div><div class="form-group"><label for="product_file">فایل اصلی محصول</label><input id="product_file" type="file" name="product_file" required><small>فایل خصوصی محصول — حداکثر 500MB</small></div></div>
        <div class="ai-publish-warning"><strong>انتشار مستقیم</strong><span>تا زمانی که بررسی محتوایی کامل نشده، بهتر است محصول به‌صورت پیش‌نویس بماند.</span></div>
        <label class="checkbox-label"><input type="checkbox" name="is_published" value="1" @checked(old('is_published'))> محصول منتشر شود</label>
        <div class="form-actions"><a href="{{ route('admin.products.index') }}" class="admin-secondary-btn">انصراف</a><button type="submit" class="admin-primary-btn">ایجاد و ارسال برای بررسی</button></div>
    </form></section>
</div>
@endsection
@push('styles')
<style>
.ai-product-page{max-width:1040px}.ai-trust-banner{display:flex;gap:13px;align-items:flex-start;margin:0 0 18px;padding:16px 18px;border:1px solid #dfe4ff;background:linear-gradient(135deg,#f7f8ff,#fff);border-radius:16px}.ai-trust-icon{width:38px;height:38px;display:grid;place-items:center;background:#eef2ff;color:#4f46e5;border-radius:12px;font-size:20px}.ai-trust-banner strong{display:block;font-size:13px}.ai-trust-banner span{display:block;color:#667085;font-size:11px;line-height:1.9;margin-top:4px}.ai-content-check{margin:4px 0 18px;padding:14px 16px;border-radius:14px;background:#f8fafc;border:1px solid #e7eaf0}.ai-check-title{display:flex;justify-content:space-between;align-items:center}.ai-check-title span{font-size:12px;font-weight:800}.ai-check-title b{font-size:10px;color:#027a48;background:#ecfdf3;padding:5px 9px;border-radius:20px}.ai-content-check p,.ai-publish-warning span{font-size:11px;line-height:1.9;color:#667085;margin:7px 0 0}.ai-publish-warning{display:flex;gap:8px;flex-direction:column;padding:12px 14px;border-radius:12px;background:#fffaeb;border:1px solid #fedf89;margin-bottom:13px}.ai-publish-warning strong{font-size:11px;color:#b54708}.ai-publish-warning span{margin:0}
</style>
@endpush
