@extends('admin.layout')
@section('title','افزودن محصول')
@section('content')
<div class="admin-page product-create-page"><div class="admin-page-head"><div><div class="admin-eyebrow">مدیریت فروشگاه · محصول جدید</div><h1>افزودن محصول</h1><p>فایل تکی، چند فایل، ZIP یا پوشه را وارد کنید؛ محتویات به‌صورت فایل‌های مستقل نمایش داده می‌شوند.</p></div><a href="{{ route('admin.products.index') }}" class="admin-secondary-btn">بازگشت</a></div>
@if($errors->any())<div class="admin-alert error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form id="productForm" method="POST" action="{{ route('admin.products.store') }}">@csrf
<section class="admin-form-card product-section"><h2>اطلاعات محصول</h2><div class="form-row"><div class="form-group"><label>عنوان محصول *</label><input name="title" required maxlength="255" value="{{ old('title',data_get($draft?->payload,'title')) }}"></div><div class="form-group"><label>دسته‌بندی *</label><select name="category_id" required><option value="">انتخاب</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div></div><div class="form-row"><div class="form-group"><label>قیمت *</label><input type="number" min="0" name="price" required value="{{ old('price',data_get($draft?->payload,'price',0)) }}"></div><div class="form-group"><label>Slug اختیاری</label><input dir="ltr" name="slug" value="{{ old('slug',data_get($draft?->payload,'slug')) }}"></div></div><div class="form-group"><label>Storage Provider</label><select id="storage_provider_id" name="storage_provider_id"><option value="">خودکار</option>@foreach($storageProviders as $provider)<option value="{{ $provider->id }}">{{ $provider->name }} — {{ strtoupper($provider->type) }}</option>@endforeach</select></div></section>
<section class="admin-form-card product-section"><h2>توضیحات</h2><div class="form-group"><label>توضیح کوتاه</label><textarea name="short_description" maxlength="1000">{{ old('short_description',data_get($draft?->payload,'short_description')) }}</textarea></div><div class="form-group"><label>توضیحات کامل</label><textarea name="description" rows="10">{{ old('description',data_get($draft?->payload,'description')) }}</textarea></div></section>
<section class="admin-form-card product-section"><h2>فایل‌های محصول</h2><div class="file-dropzone" id="dropzone"><div class="drop-icon"><x-icon name="download" size="24"/></div><strong>فایل، چند فایل، ZIP یا پوشه را اینجا بکشید</strong><span>PDF / DOC / DOCX · حداکثر ۲۰۰MB برای هر فایل</span><div class="pickers"><button type="button" class="admin-primary-btn" id="chooseFiles">انتخاب فایل</button><button type="button" class="admin-secondary-btn" id="chooseFolder">انتخاب پوشه</button></div><input id="fileInput" type="file" accept=".pdf,.doc,.docx,.zip" multiple hidden><input id="folderInput" type="file" webkitdirectory directory multiple hidden></div><div id="uploadedList" class="uploaded-list"></div><div id="uploadIds"></div><div class="file-rules"><span>✓ PDF</span><span>✓ DOC</span><span>✓ DOCX</span><span>✓ ZIP</span><span>✓ پوشه</span><span>✓ فایل‌های داخلی مستقل می‌شوند</span></div></section>
<section class="admin-form-card product-section"><div class="check-grid"><div><b>منبع حقیقت</b><span>محتوای واقعی فایل</span></div><div><b>Preview</b><span>PDF مستقل و محدود</span></div><div><b>Reader</b><span>بر اساس نوع فایل</span></div><div><b>AI</b><span>ایندکس و بررسی محتوا</span></div></div><div class="form-actions"><a href="{{ route('admin.products.index') }}" class="admin-secondary-btn">انصراف</a><button class="admin-primary-btn" type="submit">ایجاد و ارسال برای بررسی</button></div></section>
</form></div>
@endsection
@push('styles')<style>
.product-create-page{max-width:1120px}.product-section{margin-bottom:16px;padding:22px}.product-section h2{margin:0 0 18px;font-size:16px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:14px}.form-group{margin-bottom:14px}.form-group label{display:block;font-size:11px;font-weight:700;margin-bottom:7px}.form-group input,.form-group textarea,.form-group select{width:100%;border:1px solid #dfe3ea;border-radius:10px;padding:10px 12px;background:#fff;font:inherit}.file-dropzone{border:2px dashed #cfd5df;border-radius:18px;padding:34px 20px;text-align:center;background:#fafbff;display:flex;flex-direction:column;align-items:center;gap:9px}.drop-icon{width:50px;height:50px;display:grid;place-items:center;border-radius:15px;background:#eef2ff;color:#4f46e5}.file-dropzone strong{font-size:14px}.file-dropzone span{font-size:10px;color:#667085}.pickers{display:flex;gap:8px}.uploaded-list{display:grid;gap:8px;margin-top:12px}.uploaded-item{display:grid;grid-template-columns:auto 1fr auto;gap:11px;align-items:center;border:1px solid #eaecf0;border-radius:12px;padding:10px 12px}.file-type{width:38px;height:38px;display:grid;place-items:center;border-radius:10px;background:#f2f4f7;font-size:9px;font-weight:900}.uploaded-item strong,.uploaded-item small{display:block}.uploaded-item strong{font-size:11px}.uploaded-item small{font-size:9px;color:#98a2b3;margin-top:3px}.remove-file{border:0;background:#fff1f3;color:#c01048;border-radius:8px;padding:7px;cursor:pointer}.file-rules{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.file-rules span{padding:7px 9px;border:1px solid #eaecf0;background:#f8fafc;border-radius:8px;color:#667085;font-size:9px}.check-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.check-grid>div{padding:12px;border:1px solid #eaecf0;background:#f8fafc;border-radius:11px}.check-grid b,.check-grid span{display:block}.check-grid b{font-size:10px}.check-grid span{font-size:9px;color:#667085;margin-top:4px}@media(max-width:700px){.form-row,.check-grid{grid-template-columns:1fr}}
</style>@endpush
@push('scripts')<script>
(()=>{const input=document.getElementById('fileInput'),folder=document.getElementById('folderInput'),choose=document.getElementById('chooseFiles'),chooseFolder=document.getElementById('chooseFolder'),drop=document.getElementById('dropzone'),list=document.getElementById('uploadedList'),ids=document.getElementById('uploadIds'),csrf=@json(csrf_token()),url=@json(route('admin.products.uploads.store'));let uploaded=[];const fmt=n=>n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';const render=()=>{ids.innerHTML=uploaded.map(x=>`<input type="hidden" name="upload_ids[]" value="${x.id}">`).join('');list.innerHTML=uploaded.map((x,i)=>`<div class="uploaded-item"><div class="file-type">${x.extension}</div><div><strong>${x.name}</strong><small>${fmt(x.size)} · آماده ثبت</small></div><button type="button" class="remove-file" data-i="${i}">حذف</button></div>`).join('');list.querySelectorAll('.remove-file').forEach(b=>b.onclick=()=>{uploaded.splice(+b.dataset.i,1);render()})};async function send(file){const fd=new FormData();fd.append('file',file);const provider=document.getElementById('storage_provider_id').value;if(provider)fd.append('storage_provider_id',provider);const r=await fetch(url,{method:'POST',headers:{'X-CSRF-TOKEN':csrf,Accept:'application/json'},body:fd});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.message||'آپلود ناموفق بود');(d.files||[]).forEach(x=>uploaded.push(x));render()}async function handle(files){for(const f of files){try{if(f.size>209715200)throw Error('حجم فایل بیشتر از ۲۰۰MB است.');if(!/\.(pdf|doc|docx|zip)$/i.test(f.name))continue;await send(f)}catch(e){alert(f.name+'\n'+e.message)}}}choose.onclick=()=>input.click();chooseFolder.onclick=()=>folder.click();input.onchange=e=>handle([...e.target.files]);folder.onchange=e=>handle([...e.target.files]);['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>handle([...e.dataTransfer.files]));})();
</script>@endpush
