<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use App\Models\StorageProvider;
use App\Services\Storage\StorageManager;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class AdminProductController extends Controller
{
    public function index(Request $request){$q=Product::with(['category','storageProvider'])->latest();if($request->filled('q'))$q->where(fn($x)=>$x->where('title','like','%'.$request->q.'%')->orWhere('slug','like','%'.$request->q.'%'));if($request->filled('status')&&in_array($request->status,['published','draft'],true))$q->where('is_published',$request->status==='published');if($request->filled('category_id'))$q->where('category_id',$request->category_id);$products=$q->paginate(20)->withQueryString();$categories=Category::where('is_active',true)->orderBy('sort_order')->orderBy('name')->get();$storageProviders=StorageProvider::where('is_active',true)->where('scope','files')->orderBy('priority')->orderBy('name')->get();return view('admin.products.index',compact('products','categories','storageProviders'));}

    public function create(){ $categories=Category::where('is_active',true)->orderBy('sort_order')->orderBy('name')->get();$storageProviders=StorageProvider::where('is_active',true)->where('scope','files')->orderBy('priority')->orderBy('name')->get();return view('admin.products.create',compact('categories','storageProviders'));}

    public function store(Request $request,StorageManager $storageManager){$data=$this->validateData($request);$product=new Product();$product->category_id=$data['category_id'];$product->title=$data['title'];$product->slug=$data['slug'];$product->short_description=$data['short_description']??null;$product->description=$data['description']??null;$product->price=$data['price'];$product->is_published=$request->boolean('is_published');if($request->hasFile('thumbnail'))$product->thumbnail=$request->file('thumbnail')->store('products/images','local');if($request->hasFile('product_file')){$result=$storageManager->uploadTo('files',$request->file('product_file'),'products/files/'.date('Y/m').'/'.Str::uuid().'.'.$request->file('product_file')->getClientOriginalExtension(),'external',(int)($data['storage_provider_id']??0));$product->storage_provider_id=$result['provider']->id;$product->storage_path=$result['path'];$product->file_path=$result['path'];$product->file_name=$request->file('product_file')->getClientOriginalName();}else{$provider=$storageManager->select('files','external',(int)($data['storage_provider_id']??0));if($provider)$product->storage_provider_id=$provider->id;}$product->save();return redirect()->route('admin.products.index')->with('success','محصول با موفقیت ایجاد شد.');}

    public function edit(Product $product){$categories=Category::where('is_active',true)->orderBy('sort_order')->orderBy('name')->get();$storageProviders=StorageProvider::where('is_active',true)->where('scope','files')->orderBy('priority')->orderBy('name')->get();return view('admin.products.edit',compact('product','categories','storageProviders'));}

    public function update(Request $request,Product $product,StorageManager $storageManager){$data=$this->validateData($request,$product);$product->category_id=$data['category_id'];$product->title=$data['title'];$product->slug=$data['slug'];$product->short_description=$data['short_description']??null;$product->description=$data['description']??null;$product->price=$data['price'];$product->is_published=$request->boolean('is_published');if($request->hasFile('thumbnail'))$product->thumbnail=$request->file('thumbnail')->store('products/images','local');if($request->hasFile('product_file')){if($product->storage_path&&$product->storageProvider){try{$storageManager->delete($product->storageProvider,$product->storage_path);}catch(\Throwable $e){report($e);}}$result=$storageManager->uploadTo('files',$request->file('product_file'),'products/files/'.date('Y/m').'/'.Str::uuid().'.'.$request->file('product_file')->getClientOriginalExtension(),'external',(int)($data['storage_provider_id']??0));$product->storage_provider_id=$result['provider']->id;$product->storage_path=$result['path'];$product->file_path=$result['path'];$product->file_name=$request->file('product_file')->getClientOriginalName();}elseif(!$product->storage_provider_id){$provider=$storageManager->select('files','external',(int)($data['storage_provider_id']??0));if($provider)$product->storage_provider_id=$provider->id;}$product->save();return redirect()->route('admin.products.index')->with('success','محصول با موفقیت ویرایش شد.');}

    public function toggle(Product $product){$product->update(['is_published'=>!$product->is_published]);return back()->with('success',$product->is_published?'محصول منتشر شد.':'محصول از انتشار خارج شد.');}
    public function bulkAction(Request $request){$data=$request->validate(['action'=>'required|in:publish,draft,delete','ids'=>'required|array','ids.*'=>'integer|exists:products,id']);$products=Product::whereIn('id',$data['ids'])->get();foreach($products as $product){if($data['action']==='publish')$product->update(['is_published'=>true]);elseif($data['action']==='draft')$product->update(['is_published'=>false]);else $product->delete();}return back()->with('success','عملیات گروهی انجام شد.');}
    public function destroy(Product $product,StorageManager $storageManager){if($product->storage_path&&$product->storageProvider){try{$storageManager->delete($product->storageProvider,$product->storage_path);}catch(\Throwable $e){report($e);}}$product->delete();return back()->with('success','محصول حذف شد.');}
    private function validateData(Request $request,?Product $product=null):array{$unique='unique:products,slug'.($product?','.$product->id:'');return $request->validate(['category_id'=>['required','exists:categories,id'],'storage_provider_id'=>['nullable','integer','exists:storage_providers,id'],'title'=>['required','string','max:255'],'slug'=>['required','string','max:255','regex:/^[a-z0-9-]+$/',$unique],'short_description'=>['nullable','string','max:1000'],'description'=>['nullable','string'],'price'=>['required','integer','min:0'],'thumbnail'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:5120'],'product_file'=>[$product?'nullable':'required','file','max:512000']]);}
}
