<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
class AdminPanelController extends Controller{
 public function module(Request $request,string $module,?string $sub=null){abort_unless($request->user()?->hasRole('admin'),403);$titles=['users'=>'کاربران','products'=>'محصولات','orders'=>'سفارش‌ها','finance'=>'مالی','subscriptions'=>'اشتراک‌ها','assets'=>'فایل‌ها و دارایی‌ها','reader'=>'خوانشگر','loyalty'=>'باشگاه مشتریان','content'=>'محتوا','marketing'=>'بازاریابی','ai'=>'هوش مصنوعی','notifications'=>'اعلان‌ها','support'=>'پشتیبانی','reports'=>'گزارش‌ها و تحلیل‌ها','storage'=>'فضای ذخیره‌سازی','settings'=>'تنظیمات','integrations'=>'یکپارچه‌سازی‌ها','security'=>'امنیت','sellers'=>'فروشندگان','search'=>'جستجو','workflow'=>'گردش کار','tasks'=>'وظایف','system'=>'سیستم','developer'=>'مرکز توسعه‌دهندگان','newsletter'=>'خبرنامه محصولات','sms'=>'پیامک و رمز یکبارمصرف'];$subtitles=['newsletter'=>'مدیریت مشترکان، کمپین‌ها و پیشنهادهای شخصی‌سازی‌شده','sms'=>'گزارش واقعی ارسال رمز یکبارمصرف، موفقیت، خطا و انقضا','ai'=>'مدیریت مدل‌ها، مصرف، ارزیابی، پرامپت‌ها و سرویس‌های هوش مصنوعی','storage'=>'ظرفیت، مصرف، فایل‌های بزرگ و وضعیت ارائه‌دهندگان ذخیره‌سازی','reports'=>'شاخص‌های فروش، کاربران، محصولات، مالی، محتوا، هوش مصنوعی و پشتیبانی'];$title=$titles[$module]??'مدیریت سامانه';$subTitle=$subtitles[$module]??'مدیریت یکپارچه این بخش از سامانه';$subMap=['overview'=>'نمای کلی','all'=>'همه موارد','active'=>'موارد فعال','pending'=>'در انتظار بررسی','settings'=>'تنظیمات','transactions'=>'تراکنش‌ها','plans'=>'پلن‌ها','reviews'=>'نظرات','users'=>'کاربران','models'=>'مدل‌ها','providers'=>'ارائه‌دهندگان','evaluation'=>'ارزیابی مدل‌ها','usage'=>'مصرف و اعتبار','tickets'=>'تیکت‌ها','knowledge'=>'پایگاه دانش','daily'=>'گزارش روزانه','monthly'=>'گزارش ماهانه','security'=>'امنیت','logs'=>'گزارش رویدادها','quotas'=>'سهمیه‌ها'];if($sub)$subTitle=$subMap[$sub]??$subTitle;
 $stats=[['label'=>'کاربران','value'=>$this->count('users'),'icon'=>'users'],['label'=>'محصولات','value'=>$this->count('products'),'icon'=>'bag'],['label'=>'سفارش‌ها','value'=>$this->count('orders'),'icon'=>'document'],['label'=>'پرداخت‌ها','value'=>$this->count('payments'),'icon'=>'wallet']];
 if($module==='newsletter')$stats=[['label'=>'مشترکان ایمیل','value'=>$this->count('newsletter_subscribers'),'icon'=>'send'],['label'=>'فعال','value'=>$this->countWhereAny('newsletter_subscribers',['status','is_active'],['active',1]),'icon'=>'check'],['label'=>'کمپین‌ها','value'=>$this->count('newsletter_campaigns'),'icon'=>'notification'],['label'=>'کمپین ناموفق','value'=>$this->countWhere('newsletter_campaigns','status','failed'),'icon'=>'warning']];
 if($module==='sms')$stats=[['label'=>'ارسال رمز','value'=>$this->countWhere('otp_events','event','sent'),'icon'=>'send'],['label'=>'امروز','value'=>$this->countTodayWhere('otp_events','event','sent'),'icon'=>'calendar'],['label'=>'تأیید موفق','value'=>$this->countWhere('otp_events','event','verified'),'icon'=>'check'],['label'=>'خطا / انقضا','value'=>$this->countWhereIn('otp_events','event',['failed','expired']),'icon'=>'warning']];
 return view('admin.panel.module',compact('title','subTitle','module','sub','stats'));}
 private function count(string $table):int{return Schema::hasTable($table)?DB::table($table)->count():0;}private function countWhere(string $table,string $column,$value):int{return Schema::hasTable($table)&&Schema::hasColumn($table,$column)?DB::table($table)->where($column,$value)->count():0;}private function countWhereIn(string $table,string $column,array $values):int{return Schema::hasTable($table)&&Schema::hasColumn($table,$column)?DB::table($table)->whereIn($column,$values)->count():0;}private function countWhereAny(string $table,array $columns,array $values):int{if(!Schema::hasTable($table))return 0;$q=DB::table($table);foreach($columns as $i=>$column)if(Schema::hasColumn($table,$column))$q->orWhere($column,$values[$i]);return $q->count();}private function countTodayWhere(string $table,string $column,$value):int{return Schema::hasTable($table)&&Schema::hasColumn($table,'created_at')&&Schema::hasColumn($table,$column)?DB::table($table)->whereDate('created_at',now()->toDateString())->where($column,$value)->count():0;}
}