<?php
namespace App\Http\Controllers;
use App\Models\DiscountCode;use App\Models\Order;use App\Models\Product;use App\Services\Checkout\CheckoutPaymentService;use App\Services\Wallet\WalletService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class CheckoutController{
 public function index(){ $cart=session('cart',[]);if(empty($cart))return redirect()->route('cart')->with('error','سبد خرید شما خالی است.');$products=Product::whereIn('id',array_keys($cart))->where('is_published',true)->get();$valid=$products->reject(fn($p)=>$this->bought($p))->values();if($valid->isEmpty()){session()->forget('cart');return redirect()->route('cart')->with('error','تمام محصولات این سبد قبلاً خریداری شده‌اند.');}$cart=collect($cart)->filter(fn($q,$id)=>$valid->contains('id',(int)$id))->mapWithKeys(fn($q,$id)=>[(int)$id=>1])->all();session(['cart'=>$cart]);$subtotal=(float)$valid->sum('price');$discountCode=$this->getValidDiscount();$discount=$discountCode?$this->calculateDiscount($subtotal,$discountCode):0;$total=max(0,$subtotal-$discount);return view('checkout',['products'=>$valid,'cart'=>$cart,'subtotal'=>$subtotal,'discount'=>$discount,'total'=>$total,'payable'=>$total,'discountCode'=>$discountCode?->code]); }
 public function applyDiscount(Request $request){$data=$request->validate(['code'=>'required|string|max:50']);$code=DiscountCode::where('code',strtoupper(trim($data['code'])))->first();if(!$code||!$code->valid())return back()->with('discount_error','کد تخفیف معتبر نیست یا اعتبار آن به پایان رسیده است.');session(['discount_code'=>$code->code]);return back()->with('discount_success','کد تخفیف با موفقیت اعمال شد.');}
 public function removeDiscount(){session()->forget('discount_code');return back()->with('discount_success','کد تخفیف حذف شد.');}
 public function store(Request $request,WalletService $walletService){$cart=session('cart',[]);if(empty($cart))return redirect()->route('cart')->with('error','سبد خرید خالی است.');$order=DB::transaction(function()use($cart,$walletService){$products=Product::whereIn('id',array_keys($cart))->where('is_published',true)->lockForUpdate()->get();if($products->isEmpty())abort(redirect()->route('cart')->with('error','محصولات سبد خرید در دسترس نیستند.'));foreach($products as $product)if($this->bought($product))abort(redirect()->route('cart')->with('error','یکی از محصولات قبلاً خریداری شده است.'));$subtotal=(float)$products->sum('price');$discountCode=$this->getValidDiscount(true);$discount=$discountCode?$this->calculateDiscount($subtotal,$discountCode):0;$total=max(0,$subtotal-$discount);$wallet=$walletService->wallet(auth()->user());$useWallet=$total>0&&$wallet->balance>=$total;$paidNow=$total<=0||$useWallet;$order=Order::create(['user_id'=>auth()->id(),'order_number'=>$this->orderNumber(),'status'=>$paidNow?'paid':'pending','subtotal'=>$subtotal,'discount'=>$discount,'total'=>$total,'wallet_amount'=>$useWallet?$total:0,'gateway_amount'=>$useWallet||$total<=0?0:$total,'payment_method'=>$useWallet?'wallet':($total<=0?'free':'gateway'),'paid_at'=>$paidNow?now():null]);foreach($products as $product)$order->items()->create(['product_id'=>$product->id,'price'=>$product->price,'quantity'=>1]);if($discountCode){$updated=DiscountCode::where('id',$discountCode->id)->where('is_active',true)->where(fn($q)=>$q->whereNull('max_uses')->orWhereColumn('used_count','<','max_uses'))->lockForUpdate()->increment('used_count');if(!$updated)abort(redirect()->route('checkout')->with('discount_error','ظرفیت استفاده از کد تخفیف تمام شده است.'));}if($useWallet)$walletService->debit($wallet,$total,'پرداخت سفارش '.$order->order_number,Order::class,$order->id);return $order;});if($order->status==='paid'){session()->forget(['cart','discount_code']);return redirect()->route('checkout.success',$order)->with('success','سفارش شما با موفقیت پرداخت شد.');}return redirect()->route('checkout.payment');}
 public function payment(){ $order=Order::where('user_id',auth()->id())->where('status','pending')->latest()->first();if(!$order)return redirect()->route('cart')->with('error','سفارش قابل پرداختی وجود ندارد.');$order->load('items.product');return view('checkout-payment',['order'=>$order,'subtotal'=>$order->subtotal,'discount'=>$order->discount,'tax'=>$order->tax??0,'total'=>$order->total,'walletBalance'=>(int)(auth()->user()->wallet?->balance??0)]); }
 public function paymentStore(Request $request,CheckoutPaymentService $service){$data=$request->validate(['method'=>'required|in:wallet,gateway']);$order=Order::where('user_id',auth()->id())->where('status','pending')->latest()->firstOrFail();if($data['method']==='wallet'){try{$order=$service->payFromWallet($order);session()->forget(['cart','discount_code']);return redirect()->route('checkout.success',$order)->with('success','پرداخت از کیف پول با موفقیت انجام شد.');}catch(\Throwable $e){return back()->with('error',$e->getMessage());}}return redirect()->route('payment.pay',$order);}
 public function success(Order $order){abort_unless($order->user_id===auth()->id(),403);$order->load('items.product');return view('checkout-success',compact('order'));}
 private function getValidDiscount(bool $lock=false):?DiscountCode{$code=session('discount_code');if(!$code)return null;$q=DiscountCode::where('code',$code);if($lock)$q->lockForUpdate();$discount=$q->first();if(!$discount||!$discount->valid()){session()->forget('discount_code');return null;}return $discount;}
 private function calculateDiscount(float $subtotal,DiscountCode $discount):float{if($subtotal<=0)return 0;$value=$discount->is_percent?$subtotal*((float)$discount->amount/100):(float)$discount->amount;return min($subtotal,max(0,$value));}
 private function bought(Product $product):bool{return Order::where('user_id',auth()->id())->whereIn('status',['paid','completed'])->whereHas('items',fn($q)=>$q->where('product_id',$product->id))->exists();}
 private function orderNumber():string{do{$number='DS-'.now()->format('YmdHis').'-'.strtoupper(Str::random(5));}while(Order::where('order_number',$number)->exists());return $number;}
}