<?php
namespace App\Http\Controllers;
use App\Models\OrderItem;use App\Models\Product;use App\Models\ProductPreview;use App\Services\AI\ProductKnowledgeService;use App\Services\AI\ProductPdfPreviewService;use App\Services\Storage\StorageManager;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;
class ProductReaderController
{
 public function preview(Product $product,ProductKnowledgeService $knowledge,ProductPdfPreviewService $previewService,StorageManager $storage){abort_unless($product->is_published,404);$product->load('files');$documents=$product->knowledgeDocuments()->with(['chunks','file'])->get();if($documents->isEmpty()){try{$knowledge->index($product);$documents=$product->fresh()->knowledgeDocuments()->with(['chunks','file'])->get();}catch(\Throwable $e){report($e);$documents=collect();}}$pdfFile=$product->files->first(fn($file)=>strtolower((string)$file->extension)==='pdf');$pdfPreview=null;if($pdfFile){$pdfPreview=ProductPreview::where('product_file_id',$pdfFile->id)->where('source_sha256',$pdfFile->sha256)->first();if(!$pdfPreview&&config('ai.pdf_preview.enabled')){try{$pdfPreview=$previewService->make($pdfFile,$storage);}catch(\Throwable $e){report($e);}}}$pages=$this->pages($documents,7);$previewExcerpt=$pdfPreview?->excerpt?:($pages[0]['content']??$product->short_description);return view('products.reader',['product'=>$product,'pages'=>$pages,'preview'=>true,'pageLimit'=>7,'pdfFile'=>$pdfFile,'pdfPreview'=>$pdfPreview,'previewExcerpt'=>$previewExcerpt]);}
 public function read(Request $request,Product $product){abort_unless($request->user(),403);abort_unless($this->owned($request,$product),403);$product->load('files');$documents=$product->knowledgeDocuments()->with(['chunks','file'])->get();abort_if($documents->isEmpty(),404);return view('products.reader',['product'=>$product,'pages'=>$this->pages($documents,null),'preview'=>false,'pageLimit'=>null,'pdfFile'=>$product->files->first(fn($file)=>strtolower((string)$file->extension)==='pdf'),'pdfPreview'=>null,'previewExcerpt'=>null,'subscription'=>$request->user()->activeReaderSubscription]);}
 public function pdf(Request $request,Product $product,StorageManager $storage){abort_unless($product->is_published,404);$owned=$request->user()?$this->owned($request,$product):false;if($request->boolean('preview')&&!$owned){$fileId=$request->integer('file');$preview=ProductPreview::where('product_id',$product->id)->when($fileId,fn($q)=>$q->where('product_file_id',$fileId))->latest('id')->first();abort_unless($preview,404,'فایل Preview مستقل هنوز ساخته نشده است.');return $this->streamPath($preview->storageProvider?:$storage->defaultProvider(),$preview->stored_path,'preview.pdf',true);}abort_unless($owned,403);$file=$product->files()->whereRaw('LOWER(extension) = ?',['pdf'])->orderBy('sort_order')->first();abort_unless($file,404);return $this->streamStorageFile($file,$storage,false);}
 private function owned(Request $request,Product $product):bool{return OrderItem::where('product_id',$product->id)->whereHas('order',fn($q)=>$q->where('user_id',$request->user()->id)->where('status','paid'))->exists()||$request->user()->activeReaderSubscription()->exists();}
 private function streamStorageFile($file,StorageManager $storage,bool $preview){$provider=$file->storageProvider?:$storage->defaultProvider();return $this->streamPath($provider,$file->storage_path,$file->original_name,$preview);}
 private function streamPath($provider,string $path,string $name,bool $preview){abort_unless($provider->is_active,404);if($provider->type!=='local')return app(StorageManager::class)->provider($provider)->download($path,$name);$disk=$provider->config['disk']??'local';abort_unless(Storage::disk($disk)->exists($path),404);return response()->stream(function()use($disk,$path){$stream=Storage::disk($disk)->readStream($path);abort_if($stream===false,404);fpassthru($stream);fclose($stream);},200,['Content-Type'=>'application/pdf','Content-Disposition'=>'inline; filename="'.addslashes($name).'"','Cache-Control'=>$preview?'private, no-store':'private, max-age=60','X-Content-Type-Options'=>'nosniff','Accept-Ranges'=>'bytes']);}
 private function pages($documents,?int $limit):array{$pages=[];foreach($documents as $document)foreach($document->chunks->sortBy('chunk_no') as $chunk){$pages[]=['number'=>count($pages)+1,'file'=>$document->file?->original_name??'فایل محصول','extension'=>strtoupper($document->file?->extension??''),'content'=>$chunk->content,'evidence_id'=>$chunk->id];if($limit!==null&&count($pages)>=$limit)return $pages;}return $pages;}
}
