<?php
namespace App\Http\Controllers;
use App\Models\Category;use App\Models\Product;use App\Models\ProductFile;use App\Models\ProductUpload;use App\Models\StorageProvider;use App\Services\AI\ProductKnowledgeService;use App\Services\Storage\StorageManager;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class SellerProductController extends Controller
{
 public function index(){ $products=Product::where('submitted_by',auth()->id())->with('files')->latest()->paginate(20);return view('account.seller.products.index',compact('products')); }
 public function create(){ $categories=Category::where('is_active',true)->orderBy('sort_order')->orderBy('name')->get();return view('account.seller.products.create',compact('categories')); }
 public function store(Request $request,ProductKnowledgeService $knowledge){$data=$request->validate(['title'=>['required','string','max:255'],'category_id'=>['required','exists:categories,id'],'price'=>['required','integer','min:0'],'short_description'=>['nullable','string','max:1000'],'description'=>['nullable','string','max:100000'],'upload_ids'=>['required','array','min:1','max:30'],'upload_ids.*'=>['integer']]);$uploads=ProductUpload::where('user_id',auth()->id())->where('status','uploaded')->whereIn('id',$data['upload_ids'])->get();if($uploads->count()!==count(array_unique(array_map('intval',$data['upload_ids']))))return back()->withErrors(['upload_ids'=>'فایل انتخاب‌شده معتبر نیست.'])->withInput();$provider=StorageProvider::where('is_active',true)->where('is_default',true)->first()?:StorageProvider::where('is_active',true)->first();abort_unless($provider,422,'ذخیره‌سازی فعال برای فایل‌ها تنظیم نشده است.');$slug=Str::slug($data['title']).'-'.Str::lower(Str::random(6));$product=DB::transaction(function()use($data,$uploads,$provider,$slug){$p=Product::create(['category_id'=>$data['category_id'],'storage_provider_id'=>$provider->id,'title'=>$data['title'],'slug'=>$slug,'short_description'=>$data['short_description']??null,'description'=>$data['description']??null,'price'=>$data['price'],'is_published'=>false,'approval_status'=>'pending','submitted_by'=>auth()->id(),'submitted_at'=>now()]);$start=0;foreach($uploads as $upload){ProductFile::create(['product_id'=>$p->id,'storage_provider_id'=>$upload->storage_provider_id,'original_name'=>$upload->original_name,'stored_name'=>basename($upload->stored_path),'storage_path'=>$upload->stored_path,'mime_type'=>$upload->mime_type,'extension'=>$upload->extension,'size'=>$upload->size,'sha256'=>$upload->sha256,'sort_order'=>$start++]);$upload->update(['status'=>'attached','product_id'=>$p->id]);}return $p;});try{$knowledge->index($product->fresh('files'));}catch(\Throwable $e){report($e);}return redirect()->route('seller.products.index')->with('success','محصول برای بررسی ارسال شد.'); }
}
