<?php
namespace App\Http\Controllers;
use App\Models\SupportTicket;use App\Models\SupportMessage;use App\Services\AI\AIManager;use Illuminate\Http\Request;use Illuminate\Support\Facades\Cache;
class SupportController{
 public function index(){ $tickets=auth()->user()->supportTickets()->latest()->paginate(10);return view('support.index',compact('tickets'));}
 public function create(Request $request){return view('support.create',['relatedType'=>$request->query('related_type'),'relatedId'=>$request->query('related_id'),'subject'=>$request->query('subject')]);}
 public function store(Request $request,AIManager $ai){$data=$request->validate(['subject'=>'required|string|max:180','category'=>'required|in:general,product,technical,order,payment,refund,complaint,account,other','body'=>'required|string|max:10000','related_type'=>'nullable|string|max:80','related_id'=>'nullable|integer']);$sensitive=in_array($data['category'],['technical','payment','refund','complaint'],true);$ticket=SupportTicket::create(['user_id'=>auth()->id(),'subject'=>$data['subject'],'category'=>$data['category'],'related_type'=>$data['related_type']??null,'related_id'=>$data['related_id']??null,'status'=>'open','priority'=>$sensitive?'high':'normal']);SupportMessage::create(['ticket_id'=>$ticket->id,'user_id'=>auth()->id(),'sender_type'=>'user','body'=>$data['body']]);if(!$sensitive){$reply=$this->aiReply($data['body'],$ai);if($reply){SupportMessage::create(['ticket_id'=>$ticket->id,'user_id'=>null,'sender_type'=>'ai','body'=>$reply,'is_ai'=>true]);$ticket->update(['ai_handled'=>true,'status'=>'answered']);}}return redirect()->route('support.show',$ticket)->with('success','درخواست شما ثبت شد.');}
 public function show(SupportTicket $ticket){abort_unless($ticket->user_id===auth()->id(),403);$ticket->load('messages');return view('support.show',compact('ticket'));}
 public function message(Request $request,SupportTicket $ticket){abort_unless($ticket->user_id===auth()->id(),403);$data=$request->validate(['body'=>'required|string|max:10000']);SupportMessage::create(['ticket_id'=>$ticket->id,'user_id'=>auth()->id(),'sender_type'=>'user','body'=>$data['body']]);$ticket->update(['status'=>'open']);return back()->with('success','پیام شما ثبت شد.');}
 public function human(Request $request,SupportTicket $ticket){abort_unless($ticket->user_id===auth()->id(),403);$ticket->update(['human_requested'=>true,'human_requested_at'=>now(),'status'=>'human']);SupportMessage::create(['ticket_id'=>$ticket->id,'user_id'=>auth()->id(),'sender_type'=>'system','body'=>'کاربر درخواست کرده پاسخ توسط اپراتور انسانی انجام شود.']);return back()->with('success','درخواست شما به اپراتور انسانی ارجاع شد.');}
 private function aiReply(string $body,AIManager $ai):?string{$key='ai:support:'.sha1(mb_strtolower(trim($body)));return Cache::remember($key,now()->addSeconds(30),function()use($body,$ai){if(!$ai->isAvailable())return null;$result=$ai->inspectProduct(['task'=>'support_ai','system'=>'تو دستیار پشتیبانی فروشگاه فایل هستی. پاسخ فارسی، دقیق، کوتاه و بدون حدس درباره وضعیت حساب یا پرداخت بده. اگر اطلاعات کافی نیست، کاربر را برای بررسی انسانی راهنمایی کن.','prompt'=>$body,'temperature'=>0.1,'max_tokens'=>450]);return trim((string)($result['text']??''))?:null;});}
}