@extends('admin.layout')
@section('content')
<div class="admin-content ds-editor-page">
<header class="pc3-head"><div><span>مدیریت وبلاگ</span><h1>{{ $post->exists ? 'ویرایش مقاله' : 'مقاله جدید' }}</h1><p>مقاله را با ساختار حرفه‌ای، دسته‌بندی، برچسب، تصویر شاخص و محتوای غنی منتشر کنید.</p></div><a class="btn" href="{{ route('admin.blog.index') }}">بازگشت به مقالات</a></header>
@if($errors->any())<div class="pc3-alert">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form class="editor-card" method="POST" enctype="multipart/form-data" action="{{ $post->exists ? route('admin.blog.update',$post) : route('admin.blog.store') }}">@csrf @if($post->exists) @method('PUT') @endif
<section class="pc3-card"><div class="pc3-title"><b>۱</b><div><h2>اطلاعات مقاله</h2><p>عنوان، دسته‌بندی و برچسب‌ها پایه ساختار سئو و ارتباط مقالات هستند.</p></div></div><div class="pc3-grid"><label>عنوان مقاله <i>*</i><input name="title" value="{{ old('title',$post->title) }}" maxlength="255" required></label><label>دسته‌بندی واقعی<input name="category" value="{{ old('category',$post->category?->name) }}" list="blog-categories" placeholder="مثلاً آموزش، سئو، راهنمای خرید"><datalist id="blog-categories">@foreach($categories as $category)<option value="{{ $category->name }}">@endforeach</datalist></label><label>برچسب‌ها<input name="tags" value="{{ old('tags',$post->tags?->pluck('name')->implode('، ')) }}" placeholder="سئو، لاراول، فایل PDF"><small>برچسب‌ها را با ویرگول جدا کنید.</small></label><label>تصویر شاخص واقعی<input type="file" name="featured_image" accept="image/jpeg,image/png,image/webp"><small>حداکثر ۵MB. تصویر برای کارت مقاله و Open Graph نیز استفاده می‌شود.</small>@if($post->featured_image)<img class="current-featured" src="{{ asset(ltrim($post->featured_image,'/')) }}" alt="تصویر شاخص فعلی">@endif</label></div></section>
<section class="pc3-card"><div class="pc3-title"><b>۲</b><div><h2>خلاصه و سئو</h2><p>این بخش برای نتیجه جستجو، اشتراک‌گذاری و معرفی مقاله استفاده می‌شود.</p></div></div><label class="pc3-full">خلاصه مقاله<textarea name="excerpt" rows="4" maxlength="500">{{ old('excerpt',$post->excerpt) }}</textarea></label><div class="pc3-grid"><label>عنوان سئو<input name="meta_title" value="{{ old('meta_title',$post->meta_title) }}" maxlength="255"></label><label>توضیحات متا<textarea name="meta_description" rows="3" maxlength="320">{{ old('meta_description',$post->meta_description) }}</textarea></label></div></section>
<section class="pc3-card"><div class="pc3-title"><b>۳</b><div><h2>محتوای مقاله</h2><p>از H2/H3، فهرست، نقل‌قول، جدول، تصویر، رسانه و پیوند برای ساخت مقاله کامل استفاده کنید.</p></div></div><div class="ds-rich-editor" data-editor><div class="ds-editor-toolbar" role="toolbar" aria-label="ویرایشگر مقاله"><select data-cmd="formatBlock" aria-label="نوع متن"><option value="P">پاراگراف</option><option value="H1">عنوان ۱</option><option value="H2">عنوان ۲</option><option value="H3">عنوان ۳</option></select><button type="button" data-cmd="bold"><b>B</b></button><button type="button" data-cmd="italic"><i>I</i></button><button type="button" data-cmd="underline"><u>U</u></button><button type="button" data-cmd="strikeThrough">خط‌خورده</button><button type="button" data-cmd="justifyRight">راست</button><button type="button" data-cmd="justifyCenter">وسط</button><button type="button" data-cmd="justifyLeft">چپ</button><button type="button" data-cmd="insertUnorderedList">• فهرست</button><button type="button" data-cmd="insertOrderedList">۱. فهرست</button><button type="button" data-cmd="blockquote">نقل‌قول</button><button type="button" data-cmd="createLink">پیوند</button><button type="button" data-cmd="insertImage">تصویر</button><button type="button" data-cmd="insertMedia">رسانه</button><button type="button" data-cmd="insertTable">جدول</button><button type="button" data-cmd="foreColor">رنگ متن</button><button type="button" data-cmd="hiliteColor">رنگ زمینه</button><button type="button" data-cmd="removeFormat">پاک‌سازی</button></div><div class="ds-editor-content" contenteditable="true" spellcheck="true">{!! old('content',$post->content) !!}</div><textarea class="ds-editor-value" name="content" hidden></textarea></div></section>
<label class="publish-row"><input type="checkbox" name="is_published" value="1" @checked(old('is_published',$post->is_published))> انتشار مقاله</label><button class="ds-save" type="submit">{{ $post->exists ? 'ذخیره تغییرات' : 'ثبت مقاله' }}</button>
</form></div>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('css/product-editor.css') }}"><style>.ds-editor-page{padding:24px}.ds-editor-page .editor-card{max-width:1120px}.current-featured{width:min(560px,100%);max-height:280px;object-fit:cover;border-radius:12px;border:1px solid #e4e7ec}.publish-row{display:flex!important;align-items:center;gap:8px;font-size:12px;font-weight:800;margin:14px 0}.publish-row input{width:17px;height:17px}.ds-save{border:0;border-radius:12px;background:#101828;color:#fff;padding:13px 20px;font:inherit;font-weight:900;cursor:pointer}@media(max-width:700px){.ds-editor-page{padding:14px}}</style>@endpush
@push('scripts')<script src="{{ asset('js/product-editor.js') }}" defer></script>@endpush
