@extends('account.layout')
@section('title','باشگاه مشتریان')
@section('content')
<div class="club-page"><header><div><small>ارتباط بیشتر با شما</small><h1>باشگاه مشتریان</h1><p>خرید و تعامل ارزشمند شما، امتیاز و مزایای اختصاصی ایجاد می‌کند.</p></div></header><section class="club-hero"><div><span>امتیاز فعلی</span><strong>{{ number_format($points) }}</strong><small>امتیاز</small></div><div class="club-tier"><span>سطح باشگاه</span><b>{{ match($tier){'silver'=>'نقره‌ای','gold'=>'طلایی','vip'=>'ویژه',default=>'عضو'} }}</b><p>هدف بعدی: {{ number_format($next) }} امتیاز</p></div></section>
<section class="plus-card {{ $plus['active']?'active':'' }}"><div class="plus-head"><div><span>DigitalShop Plus</span><h2>{{ $plus['active']?($plus['level']==='plus-pro'?'Plus Pro فعال است':'عضویت Plus فعال است'):'مسیر رسیدن به Plus' }}</h2></div><b>{{ $plus['active']?'PLUS':'PLUS' }}</b></div><p>{{ $plus['active']?'به‌عنوان مشتری وفادار، مزایای اختصاصی برای شما فعال است.':'مشتریانی که خریدهای بیشتری دارند به‌صورت خودکار وارد برنامه Plus می‌شوند؛ نیازی به خرید اشتراک جداگانه نیست.' }}</p><div class="plus-progress"><div><span>خریدهای معتبر ۱۲ ماه اخیر</span><strong>{{ $plus['orders'] }} / {{ $plus['target_orders'] }}</strong></div><div class="progress"><i style="width:{{ min(100,($plus['orders']/$plus['target_orders'])*100) }}%"></i></div><small>{{ $plus['active']?'وضعیت فعال':'برای رسیدن به Plus هنوز '.number_format($plus['orders_left']).' خرید یا شرط هزینه باقی مانده است.' }}</small></div><div class="plus-benefits">@foreach($plus['benefits'] as $benefit)<span>✓ {{ $benefit }}</span>@endforeach</div></section>
<div class="club-grid"><article><x-icon name="gift" size="24"/><h2>پیشنهادهای هوشمند</h2><p>پیشنهادها و کدهای تخفیف بر اساس علایق و سابقه خرید شخصی‌سازی می‌شوند.</p></article><article><x-icon name="ai" size="24"/><h2>همراهی هوشمند</h2><p>دستیار هوشمند قبل از خرید و هنگام انتخاب فایل به شما کمک می‌کند.</p></article><article><x-icon name="star" size="24"/><h2>مزایای Plus</h2><p>مشتریان پرتکرار مزایای بیشتر، پیشنهادهای اختصاصی و اولویت کمپین‌های ویژه دریافت می‌کنند.</p></article></div></div>
@endsection
@push('styles')<style>.club-page{padding:15px 0}.club-page header small{color:#6541d8;font-weight:800}.club-page h1{margin:5px 0}.club-page header p{color:#667085}.club-hero{margin-top:22px;padding:25px;border-radius:22px;background:linear-gradient(135deg,#111827,#2d3151);color:#fff;display:flex;justify-content:space-between;align-items:center}.club-hero span,.club-hero small{display:block;color:#c7cad1;font-size:11px}.club-hero strong{display:inline-block;font-size:42px;margin:3px 6px 0 0}.club-tier{border-right:1px solid #ffffff25;padding-right:35px}.club-tier b{display:block;font-size:24px;margin-top:4px}.club-tier p{font-size:11px;color:#c7cad1}.plus-card{margin-top:16px;border:1px solid #e7e2fb;border-radius:22px;padding:22px;background:#faf8ff}.plus-card.active{border-color:#c9b8f4;background:linear-gradient(135deg,#faf8ff,#f2efff)}.plus-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.plus-head span{font-size:10px;color:#6941c6;font-weight:900}.plus-head h2{font-size:22px;margin:4px 0}.plus-head>b{padding:8px 12px;border-radius:9px;background:#6941c6;color:#fff;font-size:10px}.plus-card>p{font-size:11px;color:#667085;line-height:2}.plus-progress{padding:14px;border-radius:14px;background:#fff;border:1px solid #e7e2fb}.plus-progress>div:first-child{display:flex;justify-content:space-between;font-size:10px;color:#667085}.plus-progress strong{color:#344054}.progress{height:8px;background:#ece8fa;border-radius:999px;margin:9px 0}.progress i{display:block;height:100%;background:#6941c6;border-radius:999px}.plus-progress>small{font-size:9px;color:#98a2b3}.plus-benefits{display:flex;flex-wrap:wrap;gap:10px;margin-top:13px}.plus-benefits span{font-size:10px;color:#027a48;background:#ecfdf3;padding:8px 10px;border-radius:9px}.club-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:16px}.club-grid article{background:#fff;border:1px solid #e7e9ef;border-radius:18px;padding:20px}.club-grid svg{color:#6541d8}.club-grid h2{font-size:15px}.club-grid p{font-size:12px;color:#667085;line-height:2}@media(max-width:700px){.club-hero{display:block}.club-tier{border:0;border-top:1px solid #ffffff25;padding:15px 0 0;margin-top:15px}.club-grid{grid-template-columns:1fr}.plus-benefits{display:grid}}
</style>@endpush
