@extends('account.layout')
@section('title','پیشخوان')
@section('content')
<div class="account-hero"><div><span>پیشخوان شخصی</span><h1>سلام {{ $user->first_name ?: 'دوست عزیز' }}</h1><p>خریدها، فایل‌ها، باشگاه مشتریان و خدمات حساب شما در یک مرکز واحد.</p></div><a class="btn primary" href="{{ route('products.index') }}"><x-icon name="search" size="16" /> کشف فایل‌های جدید</a></div>
<div class="account-stats"><a href="{{ route('account.orders') }}"><div class="stat-icon"><x-icon name="file" size="18" /></div><small>همه سفارش‌ها</small><strong>{{ number_format($ordersCount) }}</strong><span>تاریخچه سفارش‌ها</span></a><a href="{{ route('account.orders',['status'=>'paid']) }}"><div class="stat-icon"><x-icon name="check" size="18" /></div><small>خریدهای تکمیل‌شده</small><strong>{{ number_format($paidOrdersCount) }}</strong><span>دسترسی فعال</span></a><a href="{{ route('account.files') }}"><div class="stat-icon"><x-icon name="download" size="18" /></div><small>فایل‌های من</small><strong>{{ number_format($downloadsCount) }}</strong><span>دریافت و مطالعه</span></a><a href="{{ route('account.club') }}"><div class="stat-icon"><x-icon name="ai" size="18" /></div><small>باشگاه مشتریان</small><strong>{{ number_format((int)($user->club_points??0)) }}</strong><span>امتیاز و پیشنهاد شخصی</span></a></div>
@if($pendingOrdersCount>0||$unreadNotifications>0)<div class="account-attention">@if($pendingOrdersCount>0)<a href="{{ route('account.orders',['status'=>'pending']) }}"><b>{{ $pendingOrdersCount }}</b><span><strong>سفارش نیازمند پیگیری</strong><small>وضعیت سفارش خود را بررسی کنید.</small></span><x-icon name="arrow-left" size="15" /></a>@endif @if($unreadNotifications>0)<a href="{{ route('account.notifications') }}"><b>{{ $unreadNotifications }}</b><span><strong>اعلان جدید</strong><small>پیشنهادها و پیام‌های جدید شما آماده است.</small></span><x-icon name="arrow-left" size="15" /></a>@endif</div>@endif
<div class="account-dashboard-grid"><section class="account-card"><div class="card-title"><div><small>فعالیت اخیر</small><h2>آخرین سفارش‌ها</h2></div><a href="{{ route('account.orders') }}">مشاهده همه</a></div><div class="order-list">@forelse($recentOrders as $order)<a class="order-row" href="{{ route('account.orders.show',$order) }}"><span class="order-dot"><x-icon name="file" size="15" /></span><span class="order-main"><b>{{ $order->order_number }}</b><small>{{ optional($order->created_at)->format('Y/m/d H:i') }} · {{ $order->items->count() }} قلم</small></span><span class="order-price"><b>{{ number_format($order->total) }} تومان</b><small>{{ match($order->status){'paid'=>'پرداخت‌شده','completed'=>'تکمیل‌شده','pending'=>'در انتظار پرداخت','failed'=>'ناموفق','cancelled'=>'لغوشده',default=>$order->status} }}</small></span><x-icon name="arrow-left" size="14" /></a>@empty<div class="empty">هنوز سفارشی ثبت نشده است.</div>@endforelse</div></section>
<section class="account-card club-panel"><div class="club-pattern"></div><div class="club-icon"><x-icon name="ai" size="22" /></div><small>باشگاه مشتریان</small><h2>پیشنهادهایی که برای شما ساخته می‌شوند.</h2><p>فعالیت خرید و علاقه‌مندی‌های شما به بهبود پیشنهادها و پیشنهادهای اختصاصی کمک می‌کند.</p><div class="club-points"><span>امتیاز فعلی</span><strong>{{ number_format((int)($user->club_points??0)) }}</strong></div><a class="btn light" href="{{ route('account.club') }}">ورود به باشگاه</a></section></div>
<div class="quick-grid"><a href="{{ route('account.files') }}"><x-icon name="download" size="19" /><b>فایل‌های خریداری‌شده</b><span>مطالعه و دریافت مجدد</span></a><a href="{{ route('account.wallet') }}"><x-icon name="wallet" size="19" /><b>کیف پول</b><span>موجودی و تراکنش‌ها</span></a><a href="{{ route('account.notifications') }}"><x-icon name="bell" size="19" /><b>اعلان‌های من</b><span>پیام‌ها و پیشنهادها</span></a><a href="{{ route('support.create') }}"><x-icon name="note" size="19" /><b>پشتیبانی</b><span>ثبت و پیگیری تیکت</span></a></div>
@endsection