@extends('account.layout')
@section('title','پروفایل')
@section('content')
<div class="account-head"><div><small>حساب کاربری</small><h1>پروفایل من</h1><p>اطلاعات شخصی و تصویر حساب خود را مدیریت کنید.</p></div></div>
<section class="account-card profile-card-v2"><form method="POST" action="{{ route('account.profile.update') }}" class="account-form" enctype="multipart/form-data">@csrf @method('PUT')
<div class="profile-identity"><label class="profile-avatar-upload" for="avatar"><span id="avatarPreview">@if($user->avatar_url)<img src="{{ $user->avatar_url }}" alt="">@else<x-icon name="user" size="30"/>@endif</span><i><x-icon name="file" size="14"/></i></label><div><h2>{{ trim($user->first_name.' '.$user->last_name)?:'کاربر' }}</h2><p>{{ $user->phone }}</p><small>برای تغییر تصویر روی تصویر حساب کلیک کنید.</small></div><input id="avatar" type="file" name="avatar" accept="image/jpeg,image/png,image/webp" hidden></div>
<div class="form-grid"><label>نام<input name="first_name" value="{{ old('first_name',$user->first_name) }}" required></label><label>نام خانوادگی<input name="last_name" value="{{ old('last_name',$user->last_name) }}"></label><label>شماره موبایل<input value="{{ $user->phone }}" dir="ltr" disabled></label><label>کد ملی<input name="national_code" value="{{ old('national_code',$user->national_code) }}" inputmode="numeric" maxlength="10" dir="ltr" placeholder="اختیاری"></label></div>
<div class="form-note">شماره موبایل شناسه اصلی حساب است و از این بخش قابل تغییر نیست.</div><button class="btn primary">ذخیره تغییرات</button></form></section>
@endsection
@push('styles')<style>.profile-card-v2{max-width:850px}.profile-identity{display:flex;align-items:center;gap:15px;padding:4px 0 20px;margin-bottom:5px;border-bottom:1px solid #f0f2f5}.profile-identity h2{margin:0;font-size:17px}.profile-identity p{margin:4px 0;color:#667085;font-size:10px}.profile-identity small{color:#98a2b3;font-size:9px}.profile-avatar-upload{position:relative;width:76px;height:76px;border-radius:50%;cursor:pointer;display:grid;place-items:center;background:#eef1ff;color:#304aca;border:3px solid #fff;box-shadow:0 0 0 1px #dfe3f2,0 8px 20px rgba(16,24,40,.08);overflow:visible}.profile-avatar-upload>span{width:100%;height:100%;display:grid;place-items:center;border-radius:inherit;overflow:hidden}.profile-avatar-upload img{width:100%;height:100%;object-fit:cover}.profile-avatar-upload i{position:absolute;right:-2px;bottom:-1px;width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#304aca;color:#fff;border:2px solid #fff;font-style:normal}</style>@endpush
@push('scripts')<script>document.getElementById('avatar')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);document.getElementById('avatarPreview').innerHTML='<img src="'+url+'" alt="پیش‌نمایش">'});</script>@endpush