@extends('account.layout')
@section('title','خوانشگر و اشتراک')
@section('content')
<div class="account-head"><div><small>مطالعه فایل‌ها</small><h1>خوانشگر و اشتراک</h1><p>فایل‌های خریداری‌شده را در خوانشگر مطالعه کنید و با اشتراک، دسترسی مطالعه را ساده‌تر کنید.</p></div></div>
<div class="reader-plan-grid">
<section class="account-card reader-plan-main"><span class="reader-kicker">اشتراک ماهانه</span><h2>مطالعه راحت‌تر، بدون توقف</h2><p>اشتراک خوانشگر برای {{ $days }} روز فعال می‌شود و از موجودی کیف پول پرداخت می‌شود.</p><div class="reader-price">{{ number_format($price) }} <small>تومان</small></div>@if($active)<div class="reader-active"><x-icon name="check" size="18"/><div><b>اشتراک فعال است</b><small>تا {{ $active->ends_at->format('Y/m/d H:i') }}</small></div></div>@else<form method="POST" action="{{ route('account.reader.purchase') }}">@csrf<button class="btn primary"><x-icon name="eye" size="16"/> فعال‌سازی اشتراک</button></form>@endif</section>
<section class="account-card"><div class="card-title"><div><small>وضعیت حساب</small><h2>تاریخچه اشتراک</h2></div></div>@forelse($subscriptions as $subscription)<div class="reader-history"><span>{{ $subscription->plan==='monthly'?'ماهانه':'اشتراک' }}</span><b>{{ number_format($subscription->price) }} تومان</b><small>{{ $subscription->starts_at->format('Y/m/d') }} تا {{ $subscription->ends_at->format('Y/m/d') }}</small></div>@empty<p class="empty">هنوز اشتراکی ثبت نشده است.</p>@endforelse</section>
</div>
@endsection
@push('styles')<style>.reader-plan-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:18px}.reader-plan-main{background:linear-gradient(135deg,#f4f1ff,#fff);border-color:#e5ddff}.reader-kicker{display:inline-flex;padding:5px 9px;border-radius:20px;background:#ebe7ff;color:#5b35d5;font-size:9px;font-weight:900}.reader-plan-main h2{font-size:22px;margin:13px 0 6px}.reader-plan-main>p{font-size:10px;color:#667085;max-width:600px}.reader-price{font-size:28px;font-weight:900;color:#4f2bbf;margin:18px 0}.reader-price small{font-size:9px;color:#667085}.reader-active{display:flex;align-items:center;gap:10px;padding:11px 13px;border-radius:12px;background:#ecfdf3;color:#067647;width:max-content}.reader-active b,.reader-active small{display:block}.reader-active small{font-size:8px;margin-top:2px}.reader-history{padding:12px 0;border-bottom:1px solid #f0f2f5}.reader-history:last-child{border-bottom:0}.reader-history span,.reader-history b,.reader-history small{display:block}.reader-history span{font-size:10px}.reader-history b{font-size:11px;margin:3px 0}.reader-history small{font-size:8px;color:#98a2b3}@media(max-width:800px){.reader-plan-grid{grid-template-columns:1fr}}</style>@endpush