@php($path=request()->path())
<nav class="panel-nav">
<div class="panel-nav-title">حساب کاربری</div>
<a class="{{ request()->routeIs('account.dashboard')?'active':'' }}" href="{{ route('account.dashboard') }}"><x-icon name="home" size="17"/>پیشخوان</a>
<a class="{{ request()->routeIs('account.profile','account.security')?'active':'' }}" href="{{ route('account.profile') }}"><x-icon name="user" size="17"/>پروفایل کاربری</a>
<a class="{{ request()->routeIs('account.orders*')?'active':'' }}" href="{{ route('account.orders') }}"><x-icon name="bag" size="17"/>سفارش‌ها</a>
<a class="{{ request()->routeIs('account.files')?'active':'' }}" href="{{ route('account.files') }}"><x-icon name="download" size="17"/>فایل‌های من</a>
<a class="{{ request()->routeIs('account.reader*')?'active':'' }}" href="{{ route('account.reader') }}"><x-icon name="eye" size="17"/>خوانشگر و اشتراک</a>
<a class="{{ request()->routeIs('account.club')?'active':'' }}" href="{{ route('account.club') }}"><x-icon name="gift" size="17"/>باشگاه مشتریان</a>
<a class="{{ request()->routeIs('account.wallet')?'active':'' }}" href="{{ route('account.wallet') }}"><x-icon name="wallet" size="17"/>کیف پول</a>
<a class="{{ request()->routeIs('account.notifications*')?'active':'' }}" href="{{ route('account.notifications') }}"><x-icon name="notification" size="17"/>اعلان‌ها @if($panelUnread)<b class="nav-badge">{{ $panelUnread }}</b>@endif</a>
<a class="{{ str_starts_with($path,'support')?'active':'' }}" href="{{ route('support.index') }}"><x-icon name="support" size="17"/>پشتیبانی و تیکت‌ها</a>
@if($user->hasRole('seller'))<div class="panel-nav-title">فروشنده</div><a href="{{ route('seller.products.index') }}"><x-icon name="bag" size="17"/>محصولات من</a><a href="{{ route('seller.products.create') }}"><x-icon name="add-file" size="17"/>افزودن محصول</a>@endif
@if($user->hasRole('admin'))
<div class="panel-nav-title">مدیریت سامانه</div>
@php($groups=[
'users'=>'کاربران','products'=>'محصولات','orders'=>'سفارش‌ها','finance'=>'مالی','subscriptions'=>'اشتراک‌ها','assets'=>'فایل‌ها و دارایی‌ها','reader'=>'خوانشگر','loyalty'=>'باشگاه مشتریان','content'=>'محتوا','marketing'=>'بازاریابی','ai'=>'هوش مصنوعی','support'=>'پشتیبانی','notifications'=>'اعلان‌ها','reports'=>'گزارش‌ها و تحلیل‌ها','storage'=>'فضای ذخیره‌سازی','search'=>'جستجو','sellers'=>'فروشندگان','security'=>'امنیت','settings'=>'تنظیمات','system'=>'سیستم','newsletter'=>'خبرنامه محصولات','sms'=>'پیامک و رمز یکبارمصرف']);
@php($icons=['users'=>'users','products'=>'bag','orders'=>'document','finance'=>'wallet','subscriptions'=>'clock','assets'=>'folder','reader'=>'eye','loyalty'=>'gift','content'=>'document','marketing'=>'discount','ai'=>'ai','support'=>'support','notifications'=>'notification','reports'=>'chart','storage'=>'database','search'=>'search','sellers'=>'users','security'=>'lock','settings'=>'settings','system'=>'dashboard','newsletter'=>'send','sms'=>'send'])
@php($subs=['users'=>['همه کاربران','کاربران فعال','در انتظار تأیید','نقش‌ها و دسترسی‌ها','فعالیت کاربران'],'products'=>['همه محصولات','افزودن محصول','پیش‌نویس‌ها','در انتظار تأیید','تأییدشده','ردشده','دسته‌بندی‌ها','نظرات'],'orders'=>['همه سفارش‌ها','در انتظار پرداخت','موفق','ناموفق','لغوشده','تکمیل‌شده','استرداد وجه'],'finance'=>['تراکنش‌ها','پرداخت‌ها','کیف پول','برداشت‌ها','تسویه‌ها','فاکتورها','کمیسیون‌ها','مالیات'],'subscriptions'=>['همه اشتراک‌ها','پلن‌ها','تمدیدها','تغییر پلن'],'assets'=>['کتابخانه فایل‌ها','پوشه‌ها','فایل‌های من','فایل‌های خریداری‌شده','فضای ذخیره‌سازی'],'reader'=>['کتابخانه','بوکمارک‌ها','هایلایت‌ها','یادداشت‌ها','تاریخچه مطالعه'],'loyalty'=>['مشتریان','امتیازات','سطوح','جوایز'],'content'=>['صفحات','رسانه','بنرها','نظرات'],'marketing'=>['تخفیف‌ها','کمپین‌ها','همکاری در فروش','معرفی دوستان','تبلیغات'],'ai'=>['مرکز هوش مصنوعی','مدل‌ها','ارائه‌دهندگان','ارزیابی مدل‌ها','پرامپت‌ها','تولید محتوا','مصرف و اعتبار'],'support'=>['مرکز پشتیبانی','تیکت‌ها','ارجاع‌ها','زمان پاسخ و حل','پایگاه دانش'],'notifications'=>['همه اعلان‌ها','ارسال اعلان','قالب‌ها','کمپین‌های اطلاع‌رسانی'],'reports'=>['گزارش فروش','گزارش مالی','گزارش کاربران','گزارش محصولات','گزارش محتوا','گزارش هوش مصنوعی','گزارش پشتیبانی'],'storage'=>['نمای کلی','فایل‌های بزرگ','فایل‌های قدیمی','سهمیه‌ها','تنظیمات'],'search'=>['تنظیمات جستجو','تحلیل جستجو','پیشنهادها'],'sellers'=>['همه فروشندگان','درخواست‌های فروشندگی','عملکرد','کمیسیون'],'security'=>['مرکز امنیت','ورودها','نشست‌ها','رخدادهای امنیتی','گزارش حسابرسی'],'settings'=>['عمومی','فروشگاه','پرداخت','ایمیل','پیامک','اعلان‌ها','امنیت'],'system'=>['سلامت سیستم','گزارش رویدادها','صف پردازش','حافظه موقت','پشتیبان‌گیری','حالت تعمیرات','ویژگی‌های آزمایشی'],'newsletter'=>['مرکز خبرنامه','مشترکان ایمیل','کمپین‌ها','پیشنهادهای هوشمند'],'sms'=>['مرکز پیامک','گزارش رمز یکبارمصرف','گزارش ارسال‌ها','تنظیمات پیامک']]);
@foreach($groups as $key=>$label) @php($open=str_starts_with($path,'admin/'.$key))<div class="panel-nav-group {{ $open?'open':'' }}"><button type="button" class="panel-nav-parent" aria-expanded="{{ $open?'true':'false' }}"><x-icon name="{{ $icons[$key] }}" size="17"/><span>{{ $label }}</span><x-icon name="arrow-left" size="14"/></button><div class="panel-submenu">@foreach($subs[$key]??['نمای کلی'] as $i=>$sub)<a href="{{ url('/admin/'.$key.'/'.($i===0?'overview':$i)) }}">{{ $sub }}</a>@endforeach</div></div>@endforeach
@endif
</nav>