@props(['name','value'=>'','mode'=>'product','placeholder'=>'متن خود را اینجا بنویسید…','height'=>430])
@php $editorId='ds-rich-'.preg_replace('/[^a-zA-Z0-9_-]/','-',$name).'-'.uniqid(); $fullMode=$mode==='full'; @endphp
<div class="ds-rich-editor" id="{{ $editorId }}" data-ds-editor data-mode="{{ $mode }}" data-name="{{ $name }}" style="--ds-editor-height:{{ (int)$height }}px">
<input type="hidden" name="{{ $name }}" value="{{ old($name,$value) }}" data-ds-editor-value>
<div class="ds-editor-shell">
<div class="ds-editor-toolbar" role="toolbar" aria-label="ابزارهای ویرایش متن">
<div class="ds-tool-group"><button type="button" class="ds-tool ds-tool-select" data-command="format" data-value="p"><span class="ds-tool-label">متن عادی</span><span>⌄</span></button><div class="ds-format-menu" hidden><button type="button" data-command="format" data-value="p">متن عادی</button>@if($fullMode)<button type="button" data-command="format" data-value="h1">عنوان ۱</button>@endif<button type="button" data-command="format" data-value="h2">عنوان ۲</button><button type="button" data-command="format" data-value="h3">عنوان ۳</button><button type="button" data-command="format" data-value="h4">عنوان ۴</button></div></div>
<span class="ds-tool-separator"></span>
<div class="ds-tool-group"><button type="button" class="ds-tool" data-command="bold" title="درشت"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M7 5h6a3 3 0 0 1 0 6H7zm0 6h7a3 3 0 0 1 0 6H7zM7 5v12"/></svg></span></button><button type="button" class="ds-tool" data-command="italic" title="مورب"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M10 5h8M6 19h8M14 5 10 19"/></svg></span></button><button type="button" class="ds-tool" data-command="underline" title="زیرخط"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M7 5v6a5 5 0 0 0 10 0V5M5 19h14"/></svg></span></button></div>
<span class="ds-tool-separator"></span><div class="ds-tool-group"><button type="button" class="ds-tool" data-command="insertUnorderedList" title="فهرست"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/></svg></span></button><button type="button" class="ds-tool" data-command="insertOrderedList" title="فهرست شماره‌دار"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M9 6h12M9 12h12M9 18h12M4 4v4M3 4h2M3 8h2M3 10h2l-2 4h2M3 17h2l-2 3h2"/></svg></span></button><button type="button" class="ds-tool" data-command="blockquote" title="نقل‌قول"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M9 11H5a3 3 0 0 0-3 3v2h7v-5zM22 11h-4a3 3 0 0 0-3 3v2h7v-5z"/></svg></span></button></div>
<span class="ds-tool-separator"></span><div class="ds-tool-group"><button type="button" class="ds-tool" data-command="undo" title="بازگشت"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M9 14 4 9l5-5M4 9h9a7 7 0 0 1 7 7v1"/></svg></span></button><button type="button" class="ds-tool" data-command="redo" title="جلو رفتن"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="m15 14 5-5-5-5M20 9h-9a7 7 0 0 0-7 7v1"/></svg></span></button></div>
@if($fullMode)<span class="ds-tool-separator"></span><div class="ds-tool-group"><button type="button" class="ds-tool" data-command="link" title="پیوند"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M10 13a5 5 0 0 0 7.07.07l2-2a5 5 0 0 0-7.07-7.07l-1.15 1.15M14 11a5 5 0 0 0-7.07-.07l-2 2A5 5 0 0 0 12 20l1.15-1.15"/></svg></span></button><button type="button" class="ds-tool" data-command="image" title="تصویر"><span class="ds-icon"><svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m21 15-5-5L5 20"/></svg></span></button><button type="button" class="ds-tool" data-command="code" title="کد"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="m8 9-4 3 4 3M16 9l4 3-4 3M14 5l-4 14"/></svg></span></button></div>@endif
<button type="button" class="ds-tool ds-expand" data-command="fullscreen" title="تمام‌صفحه"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M8 3H5a2 2 0 0 0-2 2v3M16 3h3a2 2 0 0 1 2 2v3M8 21H5a2 2 0 0 1-2-2v-3M16 21h3a2 2 0 0 0 2-2v-3"/></svg></span></button>
</div>
<div class="ds-editor-content" contenteditable="true" role="textbox" aria-multiline="true" dir="rtl" data-ds-editor-content data-placeholder="{{ $placeholder }}" spellcheck="true"></div>
<div class="ds-editor-footer"><span class="ds-save-state" data-ds-save-state>آماده</span><span class="ds-editor-stats"><span data-ds-words>۰</span> واژه · <span data-ds-chars>۰</span> نویسه</span><span class="ds-editor-hint">ذخیره خودکار فعال است</span></div>
</div>@if(!$fullMode)<div class="ds-editor-note"><span>✓</span> امکانات نامناسب برای توضیحات محصول غیرفعال هستند تا محتوا یکدست و مناسب SEO باقی بماند.</div>@endif
</div>
@once @push('styles')<link rel="stylesheet" href="{{ asset('css/admin-rich-editor.css') }}">@endpush @push('scripts')<script src="{{ asset('js/admin-rich-editor.js') }}" defer></script>@endpush @endonce