@props(['name','value'=>'','mode'=>'product','placeholder'=>'متن خود را اینجا بنویسید…','height'=>430])
@php($editorId='ds-rich-'.preg_replace('/[^a-zA-Z0-9_-]/','-',$name).'-'.uniqid())
<div class="ds-rich-editor" id="{{ $editorId }}" data-ds-editor data-mode="{{ $mode }}" data-name="{{ $name }}" style="--ds-editor-height:{{ (int)$height }}px"><input type="hidden" name="{{ $name }}" value="{{ old($name,$value) }}" data-ds-editor-value><div class="ds-editor-shell"><div class="ds-editor-toolbar" role="toolbar" aria-label="ابزارهای ویرایش متن">
<div class="ds-tool-group"><button type="button" class="ds-tool ds-tool-select" data-command="format" data-value="p">متن عادی ⌄</button><div class="ds-format-menu" hidden><button type="button" data-command="format" data-value="p">متن عادی</button>@if($mode==='full')<button type="button" data-command="format" data-value="h1">عنوان ۱</button>@endif<button type="button" data-command="format" data-value="h2">عنوان ۲</button><button type="button" data-command="format" data-value="h3">عنوان ۳</button><button type="button" data-command="format" data-value="h4">عنوان ۴</button></div></div><span class="ds-tool-separator"></span>
<div class="ds-tool-group"><button type="button" class="ds-tool" data-command="bold" title="درشت"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M7 5h6a3 3 0 0 1 0 6H7zm0 6h7a3 3 0 0 1 0 6H7zM7 5v12"/></svg></span></button><button type="button" class="ds-tool" data-command="italic" title="مورب"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M10 5h8M6 19h8M14 5 10 19"/></svg></span></button><button type="button" class="ds-tool" data-command="underline" title="زیرخط"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M7 5v6a5 5 0 0 0 10 0V5M5 19h14"/></svg></span></button></div><span class="ds-tool-separator"></span>
<div class="ds-tool-group"><button type="button" class="ds-tool ds-color-button" data-color-menu="text" title="رنگ متن">A</button><div class="ds-color-menu" data-menu="text" hidden><button type="button" data-command="foreColor" data-value="#1f2937" style="--swatch:#1f2937"></button><button type="button" data-command="foreColor" data-value="#315c7c" style="--swatch:#315c7c"></button><button type="button" data-command="foreColor" data-value="#176b5b" style="--swatch:#176b5b"></button><button type="button" data-command="foreColor" data-value="#8a5a00" style="--swatch:#8a5a00"></button><button type="button" data-command="foreColor" data-value="#9f3a38" style="--swatch:#9f3a38"></button></div><button type="button" class="ds-tool ds-color-button" data-color-menu="highlight" title="هایلایت">▰</button><div class="ds-color-menu" data-menu="highlight" hidden><button type="button" data-command="backColor" data-value="#fff3bf" style="--swatch:#fff3bf"></button><button type="button" data-command="backColor" data-value="#dff4ee" style="--swatch:#dff4ee"></button><button type="button" data-command="backColor" data-value="#e6eef6" style="--swatch:#e6eef6"></button></div></div><span class="ds-tool-separator"></span>
<div class="ds-tool-group"><button type="button" class="ds-tool" data-command="insertUnorderedList" title="فهرست"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/></svg></span></button><button type="button" class="ds-tool" data-command="insertOrderedList" title="فهرست شماره‌دار"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M9 6h12M9 12h12M9 18h12M4 4v4M3 4h2M3 8h2M3 10h2l-2 4h2M3 17h2l-2 3h2"/></svg></span></button><button type="button" class="ds-tool" data-command="blockquote" title="نقل‌قول"><span class="ds-icon"><svg viewBox="0 0 24 24"><path d="M9 11H5a3 3 0 0 0-3 3v2h7v-5zM22 11h-4a3 3 0 0 0-3 3v2h7v-5z"/></svg></span></button></div><span class="ds-tool-separator"></span>
<div class="ds-tool-group"><button type="button" class="ds-tool" data-command="undo" title="بازگشت">↶</button><button type="button" class="ds-tool" data-command="redo" title="جلو رفتن">↷</button></div>
@if($mode==='full')<span class="ds-tool-separator"></span><div class="ds-tool-group"><button type="button" class="ds-tool" data-command="link" title="پیوند">↗</button><button type="button" class="ds-tool" data-command="image" title="تصویر">▧</button><button type="button" class="ds-tool" data-command="code" title="کد">&lt;/&gt;</button></div>@endif
<button type="button" class="ds-tool ds-expand" data-command="fullscreen" title="تمام‌صفحه">⛶</button></div>
<div class="ds-editor-content" contenteditable="true" role="textbox" aria-multiline="true" dir="rtl" data-ds-editor-content data-placeholder="{{ $placeholder }}" spellcheck="true"></div><div class="ds-editor-footer"><span class="ds-save-state" data-ds-save-state>آماده</span><span class="ds-editor-stats"><span data-ds-words>۰</span> واژه · <span data-ds-chars>۰</span> نویسه</span><span class="ds-editor-hint">ذخیره خودکار فعال است</span></div></div>@if($mode!=='full')<div class="ds-editor-note"><span>✓</span> ابزارهای غیرضروری برای توضیحات محصول غیرفعال هستند تا محتوا یکدست و مناسب SEO بماند.</div>@endif</div>
@once @push('styles')<link rel="stylesheet" href="{{ asset('css/admin-rich-editor.css') }}">@endpush @push('scripts')<script src="{{ asset('js/admin-rich-editor.js') }}" defer></script>@endpush @endonce